CMSgov/bluebutton-web-server

apps/accounts/mymedicare_auth.py
apps/accounts/tests/test_login.py
apps/cmsblue/cms_custom.py
apps/eimm/views.py
apps/fhir/bluebutton/tests/test_utils.py
hhs_oauth_server/settings/base.py
requirements/requirements.in
requirements/requirements.txt

Mymedicare auth

---

requirements/requirements.txt
templates/include/footer.html

Only footer text change and fixing requirements file for now.

Enhance app authorization page

---

apps/extapi/templates/extapi/get_started.html

Adding custom screens

---

apps/extapi/templates/extapi/intro_step1.html

Fixes for html content

---

apps/accounts/forms.py
apps/accounts/urls.py
apps/accounts/views/core.py
templates/include/top-nav-responsive.html

- Need to rework user and developer create view and forms to make more DRY.
- Duplicated developer form and dropped Organization
- Duplicated Create_developer view.
flake8 passes locally
tests pass locally

Created Create User Account (It was missing from accounts)

---

apps/extapi/templates/extapi/intro_step1.html
apps/extapi/templates/extapi/setup_user.html
apps/fhir/bluebutton/fixtures/fhir_bluebutton_testdata.json
apps/fhir/bluebutton/models.py
apps/fhir/build_fhir/utils/utils_eob.py
apps/fhir/testac/utils/utils.py
apps/fhir/testac/views/base.py
apps/home/templates/authenticated-home.html
apps/home/views.py
hhs_oauth_server/examples/devops/cloudformation/dev-fe-pyapps-autoinstall.json
hhs_oauth_server/examples/devops/cloudformation/in_dev/dev_fe_1.json
hhs_oauth_server/examples/devops/cloudformation/in_dev/dev_fe_1with_s3.json
hhs_oauth_server/examples/devops/cloudformation/in_dev/dev_fe_2.json
hhs_oauth_server/examples/devops/cloudformation/in_dev/dev_fe_modular_user_data_1.json
hhs_oauth_server/examples/devops/cloudformation/in_dev/dev_fe_modular_user_data_2.json
hhs_oauth_server/examples/devops/cloudformation/in_dev/dev_fe_s3_access1.json
hhs_oauth_server/examples/devops/cloudformation/in_dev/modified-orig-prod-applicationspecific.json
hhs_oauth_server/examples/devops/cloudformation/snippet/dev_fe_1with_cfn.json
hhs_oauth_server/examples/devops/cloudformation/snippet/tags.json
hhs_oauth_server/examples/devops/cloudformation/virtualhost_conf.sh

Added working cloud formation script to install RDS Enabled Python Server on RHEL6.8 from scratch.

Cloud install

---

apps/accounts/management/commands/create_super_user_from_envars.py
apps/accounts/tests/test_login.py
apps/fhir/bluebutton/models.py
apps/fhir/bluebutton/utils.py
apps/fhir/bluebutton/views/read.py
apps/fhir/testac/utils/utils.py
apps/fhir/testac/views/base.py
hhs_oauth_server/examples/devops/cloudformation/vpc-pickenv-fe-pyapps-postgres.json
hhs_oauth_server/examples/devops/cloudformation/vpc-test-fe-pyapps-autoinstall.json
hhs_oauth_server/settings/base.py
hhs_oauth_server/settings/production.py
hhs_oauth_server/wsgi.py

- remove SLS and MyMedicare.gov auth from base.py
- add to production.py
- Allow manage.py create_super_user_from_envars to reset exsting admin user password
- Improve DEV TEST deplyment CF Scripts
- Add LEADER or FOLLOW option to CF Scripts
- Add settings.base as parameter with pic from list in CF Script
- Fix test_login to avoid error if SLS AUTH or MyMedicare Auth is not present
- Store fhir_supportedresourcetype.json for loading base data to databases

Improve DEV and TEST deployment

---

hhs_oauth_server/examples/devops/cloudformation/build-pyapps-base-image.json
hhs_oauth_server/settings/aws-dev.py
hhs_oauth_server/settings/aws-test.py

Created Cloud Formation Script to build Python 3.5.2+ModeWsgi RHEL 6.8 Server

Added Medicare and SLS account Auth backends to AWS-DEV and AWS-TEST

---

hhs_oauth_server/examples/devops/cloudformation/vpc-pickenv-prebuiltpy-pyapps-RDS-postgres.json

to use Pre-installed Python3.5.2/ModWsgi Image for build

Update Cloud Formation script 

---

apps/accounts/forms.py
apps/education/templates/education_0.html
apps/education/templates/education_1.html
apps/education/templates/education_2.html

- text and punctuation.
- Link to accounts_create_user
- Add Mobile Number Label in SugnupUser and SignupDeveloper
- Identify mobile number as (optional)
Flake8 passes locally
tests pass locally

Fix Education Pages:

---

apps/fhir/build_fhir/tests/test_utils.py
apps/fhir/build_fhir/utils/utils_fhir_dt.py
apps/fhir/fhir_consent/apps.py
apps/fhir/fhir_consent/signals.py
apps/fhir/fhir_consent/tests.py
apps/fhir/fhir_consent/utils.py
apps/fhir/fhir_consent/views.py

Based on discussions with privacy experts ConsentDirective DSTU2 is best format
Built create_ConsentDirective and tests
Added fhir_consent.utils to reformat scopes for inclusion in ConsentDirective
flake8 passes locally
tests pass locally

Updated Consent to create ConsentDirective

---

apps/accounts/urls.py
apps/accounts/views/core.py

Merged User and Developer Signup form. 
Also enables invitation_code and email to be passed as url parameters to GET form.

Create user generic

---

apps/accounts/emails.py
apps/accounts/models.py

Adds link with embedded invitaiton code and email

Edited Invitation email

---

apps/fhir/fhir_consent/templates/about_0.html
apps/fhir/fhir_consent/urls.py
apps/home/urls.py
hhs_oauth_server/urls.py
templates/include/top-nav-responsive.html

Make about

---

apps/accounts/ldap_auth.py
requirements/requirements.in
requirements/requirements.txt

This has been tested with ApacheDS.

Ldap auth backend

---

hhs_oauth_server/examples/devops/cloudformation/in_test/environment_script.json
hhs_oauth_server/examples/devops/cloudformation/in_test/template1-lb.json
hhs_oauth_server/examples/devops/cloudformation/in_test/vpc-pickenv-fe-db-1.json
hhs_oauth_server/examples/devops/cloudformation/in_test/vpc-pickenv-fe-lb-1.json
hhs_oauth_server/examples/devops/cloudformation/in_test/vpc-pickenv-fe-pyapps-postgres.json
hhs_oauth_server/settings/aws-impl.py

adding latest CF Scripts and settings/aws-impl.py

Impl cf edits

---

apps/fhir/bluebutton/utils.py
apps/fhir/bluebutton/views/home.py
apps/fhir/fhir_core/utils.py

using a build_querystring function in apps.fhir.fhir_core.utils
Passes flake8 locally

 fixed decoding of query parameters 

---

hhs_oauth_server/settings/aws-dev.py

STATIC_FILES_LOCATION = '/static/'
otherwise in S3 static files get /static appended to the end of the static file name.

Testing admin_static in admn/base.html

---

hhs_oauth_server/s3_storage.py

Dropping terminating slash from _normalize_name in s3_storage.py

Admin patch ignore

---

templates/include/footer.html

If admin then display Server name from settings.ALLOWED_HOSTS in footer.

Check for admin superuser in base.html

---

templates/include/footer.html

Add formatter to logging.debug in aws-dev.py
Add host name in footer is settings.DEBUG

Configure error output in DEV

---

apps/accounts/emails.py
apps/accounts/templates/email-invite-request-received.html
apps/accounts/templates/email-invite.html
apps/accounts/templates/email-invite.txt
apps/accounts/templates/email-user-code-by-email.html
apps/accounts/templates/email-user-code-by-email.txt
apps/accounts/views/core.py
templates/include/footer.html

Allow invitation_code and email to be supplied as get parameters when form is loaded.
Updated forms to add invitation_code as get parameter.
This simplifies input by pre-filling the invitation code.

Updated invitation emails and create_account function

---

apps/fhir/bluebutton/utils.py

Add Fhir_ServerVerify to apps.fhir.bluebutton.utils
Test for cx.fhir_server.Server_Verify in request_call
Apply verify=verify_state to request call.

Add Server_Verify to Fhir_Server model

---

apps/fhir/bluebutton/views/home.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/route_rud.py
apps/fhir/bluebutton/views/search.py

Updated search to check for conformance/capability and _getpages
if _getpages in request.GET make a search call.
http://issues.hhsdevcloud.us/browse/CBBP-364

Fixing next/prev searcchset bug.

---

apps/fhir/bluebutton/views/read.py
hhs_oauth_server/settings/aws-impl.py

Setting DEBUG=FALSE for IMPL environment via settings/aws-impl.py

merging develop from TH

---

README.md
hhs_oauth_server/settings/base.py

Fix the doc link broken as part of our github migration:
JIRA: https://issues.hhsdevcloud.us/browse/CBBI-274

Update doc link

---

apps/fhir/bluebutton/opoutcome_utils.py
apps/fhir/bluebutton/views/home.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py

JIRA: https://issues.hhsdevcloud.us/browse/CBBP-749
Note on base branch - I chose to compare this to an unusual branch because I did, in fact, use that as a base for this development work. This is just to make the work here clearer. I assume those changes will be merged before this, and the base branch can be safely switched back to develop.

Remove getpages and sessions

---

apps/fhir/bluebutton/views/read.py

Small bug I encountered when doing some ad hoc testing

Fix breaking bug when viewing individual item

---

hhs_oauth_server/settings/dev.py
hhs_oauth_server/urls.py

Just removing a couple items from our URLs list that are no longer working

Remove dead URLs

---

apps/dot_ext/views/authorization.py
apps/mymedicare_cb/views.py
apps/testclient/views.py

and remove ratelimit from authorize screen.

No cache testclient

---

Dockerfile
README.md
docker-compose.yml
docker-compose/custom-envvars.py
docker-compose/migrate.sh
docker-compose/readme.md

- Basic python3 Dockerfile
- docker-compose.yml defining
- a django development web server
- a postgres database
- docker-compose scripts/files for
- django migration and initial data population
- default custom-envvars.py file

Docker config files allowing for local development

---

apps/dot_ext/oauth2_validators.py

fixing redirectURI evaluation

---

apps/accounts/views/end_user_account_create.py

suppress Invite required message if REQUIRE_INVITE_TO_REGISTER is False

 test for REQUIRE_INVITE_TO_REGISTER in end_user_account_create

---

apps/accounts/views/core.py

suppress Invite required message if REQUIRE_INVITE_TO_REGISTER is False

 test for REQUIRE_INVITE_TO_REGISTER in account_create

---

apps/accounts/urls.py
apps/accounts/views/core.py
apps/accounts/views/end_user_account_create.py
apps/accounts/views/invites.py
apps/accounts/views/mfa.py
apps/accounts/views/password_reset.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/settings/test.py
requirements/requirements.in
requirements/requirements.txt

Removing ratelimiting on URLS until we can adequately test.
Also a requirement for bug bounty testing.
Will add a ticket to add it in using django rest framework next sprint.

Remove Ratelimiting

---

apps/fhir/bluebutton/views/search.py

Small change, but this feels more natural.

Update to paging math

---

templates/include/footer.html

**This link is needed for the Privacy Impact Assessment submission**.
Adding link to same Privacy Policy endpoint referenced by MyMedicare.gov
https://www.cms.gov/About-CMS/Agency-Information/Aboutwebsite/Privacy-Policy.html

Add Privacy Policy to footer

---

apps/mymedicare_cb/views.py

After speaking with Karl, this seems to be the best fix to guarantee forward compatibility. Karl will guarantee that the given URL is not broken after this deployment, and this way our data model lookup will work both today and tomorrow.

Prep for backend deployment

---

templates/design_system/do-not-approve.html

Updating a link to point to our new homepage

Update do not approve link

---

apps/fhir/bluebutton/views/read.py

read.py was splitting on | updated to split on /

CBBP-963 Update split character for beni ID from backend

---

apps/dot_ext/forms.py
apps/dot_ext/models.py
apps/dot_ext/oauth2_validators.py
apps/dot_ext/tests/test_oauth2_validators.py

In regards to this thread: https://groups.google.com/forum/#!topic/developer-group-for-cms-blue-button-api/12nJJBR9oug
Kelly and I decided it would be best to disable this feature until we have a better ability to test this and have better documentation to go along with it. I'll add a JIRA ticket to reimplement at a later date.

Remove native app redirect endpoint support

---

apps/accounts/admin.py

Enable Kelly to see newly registered users via the UserProfile Admin screen.
Columns are sortable. Adding date_joined and email.

CBBP-980: Add email and date joined to userprofile admin

---

apps/accounts/forms.py
apps/accounts/tests/test_create_account.py
apps/accounts/views/mfa.py

Remove 'Username' From Create Account view.  Sets username field to email.

Cbbp 953 - Remove 'Username' From Create Account view

---

apps/fhir/bluebutton/tests/test_utils.py
apps/fhir/bluebutton/utils.py

Another abbreviation I forgot about

Expand srtc abbreviation

---

hhs_oauth_server/settings/base.py

Enter database setting via env with sane default
directly into django's standard setting var.

Remove leaky database setting

---

apps/fhir/bluebutton/utils.py
hhs_oauth_server/request_logging.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/settings/dev_local.py

- Update request_logging.py middleware to log request/response pair info.
- Added application name/id.
- Added developer name/id.
- Added access_token_hash.
- Added location for 3xx results.
- Audit log info is contained in the top level 'message' field as JSON.

BLUEBUTTON-207 Audit log request/response pairs.

---

apps/health/checks.py
apps/health/urls.py
apps/health/views.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/urls.py

Checks the availability of
- the django app
- the database
- the data-server

BLUEBUTTON-274 Create /health endpoint

---

apps/metrics/urls.py
apps/metrics/views.py
hhs_oauth_server/urls.py

- Add User records count
- Add User active records count
- Add User staff records count
- Add User super-user/admin records count
- Add UserProfile records count
- Add DEV UserProfile records count
- Add BEN UserProfile records count
NOTE: Still working on a few more endpoints related to Jira BB #209. Wanted to make sure the approach is OK? It is testing OK so far!
Also I'm using the user.is_staff attribute for authentication, so that non-admin users can get access to the end points.
---Dave---

BLUEBUTTON-209 Add admin endpoints for count metrics

---

apps/metrics/urls.py
apps/metrics/views.py

Added application list data with unique beneficiary counts to the application admin metrics view.
---Dave---
PS: Here is an example of the JSON response:
{"count":2,"data":[{"application__id":2,"application__name":"TestApp","application__user":4,"application__user__username":"AppUser","application__user__email":"AppUser@nowhere.com","application__active":true,"unique_bene_count":5},{"application__id":3,"application__name":"TestApp2","application__user":5,"application__user__username":"App2User","application__user__email":"app2user@nowhere.com","application__active":true,"unique_bene_count":3}]}

BLUEBUTTON-208 Add data and unique bene counts to application view

---

apps/fhir/bluebutton/tests/test_utils.py
apps/fhir/bluebutton/utils.py

Minor style changes to meet flake8 standards.

Bluebuton 301 flake8

---

hhs_oauth_server/settings/base.py

Remove space in mymedicare_login_uri_ environment variable.

Correct medicare_login_uri config

---

templates/design_system/authorize.html
templates/design_system/base.html

Did the following:
* Add icon, TOS, and privacy policy to authorization
* Update for CSS grid columns and layout config
* Improve image scaling
Review the next few comments for screenshots in both the browser and mobile.

Bluebutton 188 add bene consent view

---

templates/include/top-nav-responsive.html

api.bluebutton.cms.gov should not offer login or signup on the site.
Disable Login and redirect signup to sandbox.bluebutton.cms.gov/v1/accounts/create

BLUEBUTTON-372: NAVBAR needs edit for PROD

---

apps/dot_ext/models.py
apps/dot_ext/tests/test_authorization.py
apps/dot_ext/validators.py

BLUEBUTTON-448 Allow Applications to have custom redirect schemes

---

apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/views/search.py

Provides a path forward for whitelisting and passing on query params to the data server.

BLUEBUTTON-358 Validate and transform request params to serach ep

---

apps/metrics/views.py

- Use csv renderer for pagination

BLUEBUTTON-455 Add pagination to developer metrics

---

templates/design_system/base.html

This simply adds CrazyEgg script to the template. Not sure if this is the best/only place to add this script - so I wanted some eyes on this.

520 - Adds CrazyEgg Script to template

---

apps/fhir/bluebutton/models.py
apps/metrics/views.py

This adds separate real and synthetic bene counts for each result in the application metrics admin endpoint.
Testing locally went well with a DB of 40K users and 1K apps. It returns all results with in about 8 seconds.

Bluebutton-590 Add synthetic beneficiaries to application endpoint

---

apps/authorization/admin.py
apps/authorization/permissions.py
apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/views/generic.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py
apps/metrics/urls.py
apps/metrics/views.py
apps/mymedicare_cb/tests/responses.py
apps/testclient/management/commands/create_test_user_and_application.py
templates/admin/authorization/dataaccessgrant/change_list_object_tools.html

- Also trust but verify data access on outbound data

BLUEBUTTON-572 Require an active Grant for data access

---

apps/authorization/migrations/0003_auto_20181203_1843.py

If this works it will be cherry picked down to master

Specify explicit migrations in order for Grant

---

apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/views/search.py

This reverts commit f846cd1f2e2cd19e60c485eda52cd6e997eab9e2.

BLUEBUTTON-703 Revert "Pass paging off to the fhir data-server (#683)"

---

hhs_oauth_server/settings/base.py

Changing the STATIC_URL setting back to the original. This may be affecting the CSS on the last deploy to DEV.

BLUEBUTTON-192 Revert STATIC_URL setting back to original

---

hhs_oauth_server/settings/base.py

This should fix the collectstatic issue.

BLUEBUTTON-192 Fix setup issue

---

apps/testclient/views.py

- prevents errors when patient doesn't have records.
suspect this also relates to BLUEBUTTON-607

BLUEBUTTON-608 Robust userinfo logic in testclient

---

apps/dot_ext/models.py

I think this covers what is needed. Let me know if there's anything else I need to do. Tested locally and the text seems to be updated just fine.

BLUEBUTTON-737 Updates help text.

---

apps/accounts/end_user_signup_forms.py
apps/accounts/forms.py
apps/accounts/models.py
apps/accounts/tests/test_mfa.py
apps/accounts/views/core.py
apps/accounts/views/mfa.py

Summary:
* Removed the SMS option from the MFA_CHOICES.
* Removed mobile phone number from forms and views.
* Removed SMS logic from views.
* Removed test for SMS MFA.

BLUEBUTTON-669 Remove text message MFA

---

requirements/requirements.dev.txt
requirements/requirements.txt

Summary:
* This upgrades Django version 2.1.2 to 2.1.7
* This upgrades PyYAML version 3.13 to 4.2b4 (affects local development only and doesn't need a vendor package)
* Tested well in local docker setup.

BLUEBUTTON-746 Package upgrades

---

apps/dot_ext/admin.py
apps/dot_ext/models.py

This adds list display and filter fields to the Application Label ADMIN list view.

Add list display/filter to Application Label ADMIN list view.

---

apps/accounts/templates/registration/login.html
templates/include/messages-new-fmt.html

Summary:
This PR is to merge the hot fix changes from the release-37 branch in to master.
The login page template was still containing a mockup example that didn't get noticed in testing. This was changed to use a new include/messages-new-fmt.html template with the new design for the login page.

Release r37 hot fix

---

apps/accounts/models.py
apps/metrics/views.py

Adds the user's self identification label to the admin developers list endpoint and filtering with ModelMultipleChoiceFilter().

BLUEBUTTON-970 Add identification label to developers endpoint

---

.github/pull_request_template.md

Provide a template for a github pull request that includes:
- changes
- security implications
- intentions
- requests for comments
- external links

A template to follow when creating a PR in github

---

apps/wellknown/urls.py
apps/wellknown/views/__init__.py
apps/wellknown/views/public_applications.py

This change set creates a ~public~ resource that describes the applications currently authorized to make use of the BB2.0 oAuth service. The resource is published according to a specification which may become a standard among certain resource providers, [described here](https://github.com/ekivemark/BlueButton_app_list).
- Completeness of required fields
- Configurability of `organization` information
- Correctness of resource location on the path.
```json
{
"next":null,
"previous":null,
"count":1,
"publisher":{
"organization":"The U.S. Centers for Medicare & Medicaid Services (CMS)",
"endpoints":{
"name":"metadata",
"address":"/v1/fhir/metadata"
},
"contacts":[
{
"system":"email",
"value":"foo@bar.cms"
}
]
},
"results":[
{
"name":"TestApp",
"description":"A test application", …
```

Public applications

---

apps/accounts/admin.py
apps/dot_ext/oauth2_validators.py
apps/fhir/bluebutton/utils.py
apps/metrics/views.py
apps/mymedicare_cb/authorization.py
hhs_oauth_server/settings/base.py
templates/email/email-activate.html
templates/email/email-password-forgot-link.html
templates/include/foot.html

Implement suggestions from LGTM.com
- Corrections make sense
- Changes do not change behavior
Questions, comments, concerns. Especially any observed risks from changes.
- [BLUEBUTTON-1326](https://jira.cms.gov/browse/BLUEBUTTON-1326)

Implement recommended changes from lgtm.com

---

static/js/sandbox-main.js
templates/include/app-form-optional-info.html

Changes here are relatively simple and are outlined and scoped pretty well to each commit. This work centers mostly around keyboard navigation, IE, and screen reader roles.
The file upload task is dependent on [this PR for the CSS](https://github.com/CMSgov/bluebutton-css/pull/35). No huge changes, just keeping things in order. 
Probably just want to make sure that no fixes effect the readability of the code or the feature's functionality. They are all simple fixes, so I don't think this is the case.
- [BLUEBUTTON-1337](https://jira.cms.gov/browse/BLUEBUTTON-1337)
No new dependencies or security considerations that I am aware of. This seems like some pretty straightforward enhancements.

BLUEBUTTON-1337 Sandbox UI - Accessibility Improvements

---

templates/include/app-form-required-info.html

After some research, I ended up only implementing one fix. The fix that you'll see is a little bit of a hack, but I have tested it and it works. Essentially there was this annoying behavior where when you go to register an application, the "Application Name" field would get autocomplete suggestions of what the user has entered in fields before - so I saw a lot of "John French" and so on.
Apparently, `autcomplete="off"` is deprecated and ignored by modern browsers. But if you put in a random string, the browser decides to not autocomplete. So again, it is a little bit hacky but it makes the experience nicer.
**Things I researched and decided to leave as they are:**
- In Firefox, there is this annoying functionality where it constantly thinks the client id/secret are actually user …

BLUEBUTTON-1335 Bug Fixes for Application Registration Form

---

hhs_oauth_server/settings/base.py
templates/design_system/base.html
templates/include/foot.html

Remove references to the now unused tealium tool
All references to tealium are removed. No cookie or other artifacts for tealium show up in the browser while using the system.
Does this look like everything? Can you find other references or artifacts?
- [BLUEBUTTON-1611](https://jira.cms.gov/browse/BLUEBUTTON-1611)

Remove references to tealium

---

templates/design_system/include/foot.html
templates/include/foot.html

Per the audit remediation, I've updated the link to the bootstrap CDN to be the most current version as well as the jQuery link.
I did some cursory testing and it did not appear that either effected the functionality of the site in any way.
Confirm the versions of Bootstrap/jQuery have been updated.
Make sure I am not missing any references, but I think these two might take care of it.
- [BLUEBUTTON-1600](https://jira.cms.gov/browse/BLUEBUTTON-1600)
Note: no new dependencies, but the existing dependencies are being updated for the sake of better security.

BLUEBUTTON-1600 Updates bootstrap and jquery versions from audit results

---

apps/mymedicare_cb/README.md
apps/mymedicare_cb/views.py

Adds reference in code to the SLS auth workflow in Confluence. THe link to Confluence is in the apps/mymedicare_cb/README (seemed the most appropriate place), and I've added a reference to the README in the views.py code that deals with the auth flow (rather than the Confluence link again to avoid duplication). 
- Reference confluence (documentation) in comments
Are these the most useful places for you to see the link to the docs?
- [BLUEBUTTON-1682](https://jira.cms.gov/browse/BLUEBUTTON-1682)

BLUEBUTTON-1682 Reference SLS workflow docs

---

apps/accounts/admin.py

This allows filtering of users by type in the users admin panel, which
can be used to delete selected users.
Needed in order to selectively reset user records
Note that a confirmation page is presented before action is taken with
the resulting type and number of entries to be deleted
Does this provided the needed behavior?
This removes some other user filters from the page, should it be attempted to keep those?
Are there security concerns?
- [BLUEBUTTON-1684](https://jira.cms.gov/browse/BLUEBUTTON-1684)
None.

BLUEBUTTON-1684 Filter admin list of users by type

---

apps/authorization/signals.py
apps/dot_ext/signals.py
apps/dot_ext/views/authorization.py
apps/fhir/bluebutton/tests/test_models.py
apps/logging/__init__.py
apps/logging/apps.py
apps/logging/signals.py
apps/mymedicare_cb/tests/test_callback.py
apps/mymedicare_cb/views.py
apps/test.py

Adds explicit logging around app approvals and bene login events.
Logs are present and meaningful.
Is the correct information captured?
No PII or PHI, please confirm in reviews.

Explicitly log app approvals

---

apps/accounts/management/commands/reset_beneficiaries.py

A management command is created that will
remove the BENE (BEN user type) accounts one by one. On failure it will
log and continue on, allowing for future cleanup.
- Sufficient logging etc.
- Correct query (only beneficiary accounts).
- Correct behavior.

Create the ability to reset the bene accounts

---

apps/accounts/management/commands/reset_beneficiaries.py

Correctly print exception in reset_beneficiaries management command
Matches change that was tested

Fix printing an exception

---

apps/fhir/bluebutton/authentication.py
apps/mymedicare_cb/models.py

If somehow a fhir-id and hicnhash pair became corrupted this would
prevent login for that pair.
Prevents login of a corrupted account.
Is this necessary? Does it present any problems?
Restricts access from corrupted accounts.

Assert consistent fhir-id

---

apps/accounts/forms.py
apps/accounts/templates/account-settings.html
apps/accounts/templates/registration/passwd_change_form.html
apps/accounts/views/core.py
templates/include/top-nav-responsive.html

A while back, we updated the UI of the developer sandbox. Somehow this page got left behind and this PR is meant to finally update it. Upon examination of this page, I also found some issues with the reset password flow.
**Before: Account Page**
**After: Account Page**
**Before: Problems with Password Reset Page**
**After: Fixed Password Reset Page (with cleaned-up error messages)**
- Do the changes to the account settings page look/behave as expected
- Does the updates to the change password flow make sense/still work
**Open Questions:**
- On this form, there is a "create applications" checkbox. I don't know what that means, but it is kind of confusing. What is the purpose of this checkbox? Is there a way it could be clearer.
- Should we have some short explanation why a user can't …

BLUEBUTTON-1526 Format User Account Settings Page

---

apps/testclient/views.py

Remove patient requirement in test eob function and update callback to fetch patient info from token as a fallback.
Before this the EOB endpoint would return a 403 if demographic info was
restricted by the patient.
(note the scopes, and the presence of patient_id)
(wasn't sure how to show this, but eob call is returning.
- [BLUEBUTTON-1647](https://jira.cms.gov/browse/BLUEBUTTON-1647)

Remove patient requirement in test eob function

---

templates/bene_404.html

This changes the text in the 404 response template for when a beneficiary does not have data in the system.
The text was changed from:
`BlueButton doesn't have claims data for you just yet. Please try again later.`
TO:
`Medicare is unable to retrieve your data at this time due to an internal issue. Our team is aware of the issue and is working to resolve it. Please try again at a later time. We apologize for any inconvenience.`
That the 404 response has the text changed as expected.
- [BLUEBUTTON-1927](https://jira.cms.gov/browse/BLUEBUTTON-1927)

BLUEBUTTON-1927 Modify response when bene does not have data.

---

apps/fhir/bluebutton/admin.py

Related to removing the ResourceRouter feature, there is a minor bug in the Django ADMIN Crosswalk model's search functionality that is producing a 500-error.  This removes the related display and search fields to resolve.
That the Django ADMIN search is working for the Crosswalk.
- [BLUEBUTTON-1893](https://jira.cms.gov/browse/BLUEBUTTON-1893)

BLUEBUTTON-1893 Fix issue in crosswalk admin search.

---

apps/mymedicare_cb/views.py

Summary:
This PR is to merge the hot fix changes from the release-50 branch in to master.
BB Team just deployed the BB2-54 MBI related code to Sandbox. The deployment caused a high severity bug as it is currently affecting sandbox.  The team has identified the bug, the SLS endpoint is returning an empty string value for the MBI for **SOME** of the synthetic beneficiary accounts. This empty string MBI value is causing a 500 error when the value is empty. This is due to a model level `hash_mbi` function ASSERT check for the value of mbi = "" not being allowed, similar to the check for the hicn_hash function.
**NOTE:  The release-50 branch is to be used for the deployments instead of cutting a new release from master.**
That the code change fixes the bug.
I was able to reproduce and fix the …

Release r50 hot fix

---

.github/pull_request_template.md

Please see the primary discussion and feedback of this template here: https://github.com/CMSgov/cms-oeda-dasg/pull/1
Any project specific feedback in this PR appreciated!

Update PR template to use DASG template

---

docker-compose.yml

[BFD-156](https://jira.cms.gov/browse/BFD-156)
https://github.com/CMSgov/bluebutton-web-deployment/pull/1385
Move to using bfd.cms.gov domain from bfdcloud.net
This fixes a missed (or perhaps non-existent at the time of implementation) configuration where our local docker compose setup was still pointing to bfdcloud.net rather than bfd.cms.gov.
Nothing particularly, I've tested this against our local setup with the default token successfully.
* Does this PR add any new software dependencies? …

BFD-156: Update local docker compose file to use new BFD domain

---

README.md
docker-compose/readme.md
runtests.py

[BB2-249](https://jira.cms.gov/browse/BB2-249)
As a BB2 Developer, I need the ability to run specific Django unit tests so that I can reduce the development time in the local development environment.
This updates the runtests.py python script that runs the DJango unit tests to take a list of specific tests as command line arguments. The script currently runs ALL of the tests—taking much more time.
For example, when working in a certain area of the code and creating a related test, it will save time by just being able to run that specific test.
Example:  docker-compose exec web python runtests.py apps.dot_ext.tests.test_templates.TestDOTTemplates.test_application_list_template_override
See the docker-compose/readme.md for more examples in the …

BB2-249 Update runtests.py to run specific tests for local dev

---

apps/dot_ext/tests/test_app_form_templates.py
requirements/requirements.dev.in
requirements/requirements.dev.txt
templates/include/app-form-optional-info.html

[BB2-239](https://jira.cms.gov/browse/BB2-239)
As BB2 sandbox user, I want to create an application with optional info such as "support phone number" default to blank (empty string) when I don't input anything in that field.
Currently, when Application model's support_phone_number is NULL (default), a string "None" is rendered in the field, that cause phone number validation error when the form is submitted (validation occur before model record saving).
A/C
I know the issue is fixed, when an application is created and at Edit Application page, the support phone number field is not pre-populated with None.
There is workaround:
use can clear up the field with empty string if there is no phone number to provide.
below change has been made so …

BB2-239-BB2-Fix-app-form-ph_num-initvalue-invlid

---

apps/logging/serializers.py
apps/logging/signals.py

[BB2-135](https://jira.cms.gov/browse/BB2-135)
BFD-Insights requires that user related events include the fhir_id as a new field. 
Currently, BB2 audit logger (logger id = audit.data.fhir) log audit event on BFD FHIR resource query, the event includes fields as shown below among other request generic fields:
- uuid from header BlueButton-OriginalQueryId
- user from header BlueButton-BeneficiaryId   example value: patientId:-20140000008325
- start_time from header BlueButton-OriginalQueryTimestamp
- path from header BlueButton-OriginalUrl
- application:
- name from header BlueButton-Application
- id from header BlueButton-ApplicationId
- user:
- id from header BlueButton-DeveloperId
This PR make changes in FHIRResponse serializer - the event …

BB2-135-Add-FHIR-ID-to-log-event-for-BFD-Insights

---

apps/dot_ext/views/authorization.py
apps/logging/signals.py
apps/testclient/views.py
hhs_oauth_server/request_logging.py

[BB2-224](https://jira.cms.gov/browse/BB2-224)
This is a follow up for the BB2-224 PR #823 work.
When deployed out to Sandbox we noticed that the `auth_uuid` in the session was continuing to be used in the logging after the authorization flow was completed for some applications. For example, it was being included in logging for resource end point calls.
This simply adds code at the very end of the auth flow to remove it from the session.
* TODO
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document …

BB2-224 Delete auth_uuid from session when done using it

---

apps/dot_ext/loggers.py

Summary:
This PR is to merge the hot fix changes from the release-54 branch in to master.
BB Team just deployed the BB2-276 "Improve Beneficiary Authorization Flow Log Tracing (#834)" related code to Sandbox in release r54.
We are getting 500 errors related to a `django.core.models:MultipleObjectsReturned` exception in the flowing location of the logging code:  https://github.com/CMSgov/bluebutton-web-server/blob/3709660904f83382b34a8ec784f14c9a62d83d60/apps/dot_ext/loggers.py#L170
The team has identified the bug.  Checks where added for the case where `code = None` and an exception handler was added for `MultipleObjectsReturned`. Similar code was added for the `state` value.
* Are there …

Release r54 hot fix

---

apps/dot_ext/tests/test_verify_bfd_headers.py
apps/fhir/bluebutton/utils.py
apps/fhir/bluebutton/views/generic.py
apps/fhir/server/authentication.py
apps/logging/serializers.py
apps/logging/signals.py
apps/mymedicare_cb/tests/test_callback.py

[BB2-279](https://jira.cms.gov/browse/SOMEPROJECT-42)
As BB2, I need to inject request header "includeAddressFields" = False when send FHIR resource requests to BFD in order NOT INCLUDE newly added derived address lines etc. in the Patient resource.
BFD side work is tracked by BFD-379.
A/C
I know this is done when requests from BB2 to BFD for patient resource always have the header present and its value is False
Also the returned Patient resources DO NOT have the newly added derived address lines & beneficiary city.
- DRVD_LINE_1_ADR
- DRVD_LINE_2_ADR
- DRVD_LINE_3_ADR
- DRVD_LINE_4_ADR
- DRVD_LINE_5_ADR
- DRVD_LINE_6_ADR
- CITY_NAME
- Tests are added to cover this header
1. Add "includeAddressFields" = False in addition to all the existing …

BB2-279-add-header-includeAddressFields-to-fhir-requests

---

splunk/bb2_splunk_authorization_flow_dashboard.xml

[BB2-277](https://jira.cms.gov/browse/BB2-277)
This adds some updates to the Splunk BB2 Authorization Flow Dashboard.
The following was updated:
* Greatly improved performance by utilizing 13x base searches. All other searches utilize the results of these. The dashboard now loads about 10x faster.
* Updated for newly added logging fields from the P2 scopes release.
* Updated the DEMOGRAPHIC SCOPES STATISTICS section at the end of the dashboard.
* Are the unit tests complete? Can you think of additional tests to perform?
* Are there any unhandled and/or untested edge cases you can think of?
* Does this make any backwards-incompatible changes that might break end user …

BB2-277 Update Splunk Auth Flow Dashboard

---

apps/accounts/views/oauth2_profile.py
apps/authorization/permissions.py
apps/authorization/test_data_access_grant.py
apps/authorization/tests/test_data_access_grant.py
apps/dot_ext/tests/test_authorization.py
apps/dot_ext/tests/test_views.py
apps/dot_ext/urls.py
apps/dot_ext/utils.py
apps/dot_ext/views/__init__.py
apps/dot_ext/views/authorization.py
apps/fhir/bluebutton/permissions.py
apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/views/generic.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py
apps/messages.py
hhs_oauth_server/settings/base.py
templates/app_inactive_403.html

[BB2-149](https://jira.cms.gov/browse/BB2-149)
As a Product Owner
I want to ensure we have a clear process for disabling applications 
including the removal of access tokens
so that we can easily turn off a "bad player" 
I know this is done when the process is identified and documented in confluence. 
[More details about this admin tool refer to confluence page (How can an application be disabled including active requests (administratively)):](https://confluence.cms.gov/pages/viewpage.action?pageId=361642336) 
After compare alternative approaches for implementation:
- Leverage Django Waffle flag
- Use legacy Application.active and User.is_active flags in Django Admin Models to deny access to auth and fhir flow if an application is not active …

BB2-149-Block-App-With-Active-Reqs-PR-2

---

apps/capabilities/permissions.py
apps/capabilities/tests.py
apps/fhir/bluebutton/models.py
apps/fhir/bluebutton/tests/test_models.py
apps/mymedicare_cb/models.py
apps/mymedicare_cb/tests/test_callback.py
apps/mymedicare_cb/tests/test_models.py
apps/mymedicare_cb/views.py

[BB2-237](https://jira.cms.gov/browse/BB2-237)
As a BB2 Developer, I need to improve exception handling by replacing the usage of ASSERTs in the code base so that I can more easily troubleshoot and alert on edge case issues that arise.
In general, the ASSERT type statements are converted to exceptions with handling. 
The following is a list of changes from the commits:
* Replace assert in apps/capabilities/permissions.py
- Replace assert with UpstreamServerException in apps/capabilities/permissions.py TokenHasProtectedCapability.has_permission()
- Create test_protected_path_token_has_no_scope_attribute() unit test to check for exception condition in apps/capabilities/tests.py TestTokenHasProtectedCapabilityScopesSwitchTrue
* Replace asserts …

BB2-237 Replace asserts with exception handling

---

apps/dot_ext/tests/test_authorization.py

[BB2-345](https://jira.cms.gov/browse/BB2-345)
This updates the PKCE tests to include the confidential client_type. This only updates PKCE tests and not any of the related PKCE functionality in the application code.
The following is a list of changes from the commits:
* Update PKCE tests for confidential client_type
- Rename existing public client tests to test_post_with_invalid_non_standard_scheme_granttype_authcode_clienttype_public() and test_post_with_valid_non_standard_scheme_granttype_authcode_clienttype_public()
- Add tests for confidential client_type test_post_with_valid_non_standard_scheme_granttype_authcode_clienttype_confidential() and test_post_with_invalid_non_standard_scheme_granttype_authcode_clienttype_confidential()
If …

BB2-345 Update PKCE tests

---

apps/dot_ext/admin.py

[BB2-340](https://jira.cms.gov/browse/BB2-340)
As an administrator within Django, I want to be able to easily view Apps by their Active Status to aid in metrics collection and troubleshooting. 
A/C:
In MyApplicationAdmin (Django Admin):
Application model field "active" is added to list_display and list_filter
On Django Admin UI, go to "My Application", a field "active" is shown and on the filters area, a filter "By active" is shown, filter values: All, Yes, No, selecting All, the table will show all applications with "active" = Yes and No, select "Yes", will show only applications with active=Yes (True), select "No", will show only applications with active = No (False)
Change Django Admin class MyApplicationAdmin such that model field …

BB2-340-Django-Admin-MyApplication-view-show-and-filter-by-active-field

---

hhs_oauth_server/settings/base.py

[BB2-62](https://jira.cms.gov/browse/BB2-62)
Adjusts password policy settings to meet requirements.
Adjusts password policy settings to meet requirements.  Specifically these two things are now fixed:
```
MaximumPasswordAge = sixty (60) days
PasswordHistorySize = six (6) passwords
```
* Ensure I'm reading the ticket requirements correctly
* Does this PR modify or …

BB2-62: Adjust password policy to meet requirements

---

apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/tests/test_read_and_search.py
apps/fhir/bluebutton/urls.py
apps/fhir/bluebutton/views/generic.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py
apps/logging/test_audit_loggers.py

[BB2-15](https://jira.cms.gov/browse/BB2-15)
As a user of bb2 I want the system to be reliable. Simplifying the pass through logic to the bfd into distinct endpoints will clarify the system making future work faster and more stable.
This separates out the /v1/fhir resources in their own URL patterns and derived ReadView and SearchView classes.
The following is a list of changes from the commits:
* Refactor in to separate read view endpoints
- Refactor urlpatterns for separate Patient, Coverage, and EOB in apps/fhir/bluebutton/urls.py
- Refactor ReadView in to derived classes for ReadViewPatient, ReadViewCoverage, and ReadViewExplanationOfBenefit in apps/fhir/bluebutton/views/read.py
- Update to change named URLs and remove resource_type …

BB2-15 Separate FHIR resource endpoints

---

splunk/bb2_splunk_authorization_flow_dashboard.xml

[BB2-354](https://jira.cms.gov/browse/BB2-354)
This adds some minor updates to the Splunk BB2 Authorization Flow Dashboard.
* Are the unit tests complete? Can you think of additional tests to perform?
* Are there any unhandled and/or untested edge cases you can think of?
* Does this make any backwards-incompatible changes that might break end user clients?
* Can you find any bugs if you run the code locally and test it manually?
* Naming in general? Do the namings of variables, methods, classes, and other items make sense? Are they too verbose, or not verbose enough? Any redundancies? Are the comments descriptive enough?
* Are audit logging items properly handled? Is …

BB2-354 Minor update to Splunk auth flow dashboard

---

apps/logging/test_audit_loggers.py
apps/test.py

[BB2-312](https://jira.cms.gov/browse/BB2-312)
Regression tests should be added for critical audit logging events, such as the new authorization flow logging.
the test capture the following loggers (all logging audit events) in test setup:
token_logger = logging.getLogger('audit.authorization.token')
sls_logger = logging.getLogger('audit.authorization.sls')
fhir_logger = logging.getLogger('audit.data.fhir')
authenticate_logger = logging.getLogger('audit.authenticate.sls')
mymedicare_cb_logger = logging.getLogger('audit.authenticate.mymedicare_cb')
match_fhir_id_logger = logging.getLogger('audit.authenticate.match_fhir_id')
hhs_oauth_server_request_logger = logging.getLogger('audit.hhs_oauth_server.request_logging')
then generate requests at …

BB2-312 Create audit logging regression tests

---

apps/mymedicare_cb/tests/mock_url_responses_slsx.py

[BB2-441](https://jira.cms.gov/browse/BB2-441)
As BB2, I want local run of unittests pass from different contexts:
(1) Start BB2 docker container by : docker-compose up -d web, then run: docker-compose exec web python runtests.py
(2) Start BB2 docker container by run the private script: docker_run_web_with_userid_hash_secrets.sh then attach to it by:
docker exec -it <container-name> bash, then in the container run: tox
both (1) and (2), there are errors, see jira ticket for diagnosis.
this PR extends the MOCK interceptor to accept different SLSX end points URLS with different netloc's.
e.g. in addition to "dev.accounts.cms.gov", also accepts: "test.accounts.cms.gov", "test.medicare.gov" which coming from docker-compose.yml by default.
If …

BB2-441-SLSX-unittests-errors

---

docker-compose/run_integration_tests_local_keybase.sh

[BB2-451](https://jira.cms.gov/browse/BB2-451)
As BB2 developer (developing on windows machine), I want to take advantage of re-engineered BB2 integration tests to check my work on BB2 code is free of regression and work as expected end to end (e.g. against BFD backend on prod-sbx).
Currently, the script ./docker-compose/run_integration_tests_local_keybase.sh when run with argument 'dc' does not work (see error stacks attached), due to docker-compose volume mapping not working as expected, which lead to TLS certs not found in container.
A not perfect fix provided which can get local run of BB2 integration tests going.
A/C:
After the fix, BB2 integration tests can be run on local machine (including windows), and sensitive artifacts got …

BB2-451-Fix-integration-test-script-for-localmode-Windows

---

docker-compose/bluebutton_server_start.sh
docker-compose/migrate.sh
docker-compose/readme.md
docker-compose/run_integration_tests_local_keybase.sh

… option.
[BB2-466](https://jira.cms.gov/browse/BB2-466)
As BB2 developer, I want a local mode for integration tests where a local bfd is used as backend, with this mode, BB2 developer can run integration tests:
(1) when remote BFD is not available
(2) when test some test cases that requires bfd data that has not become available yet on remote BFD e.g. prod sandbox
A/C:
a local mode is added in addition to current 'dc' mode and 'cbc' mode
bonus addition: support debugging by adding 2 extra mode:
'local-debug' and 'dc-debug' where tests are run waiting on port 5678 to attach to.
Add logic to docker-compose/run_integration_tests_local_keybase.sh, allow use of local bfd as backend
also add -debug option for 'local' and 'dc' modes respectively. …

BB2-466-Add-local-mode-to-integration-tests

---

hhs_oauth_server/request_logging.py

[BB2-486](https://jira.cms.gov/browse/BB2-486)
As BB2 community developer, I need to create BB2 Apps with my app's logo (jpg with dimension restriction).
It is noticed that this can not be done on master.
A/C
Can create apps with logo.
Fix request body decoding in audit.hhs_oauth_server.request_logging so that when request.body contains binary contents, the error is not raised (hence break the request processing, and result in the app is not created).
Note, the issue only exists when creating app with logo, creating app with no logo will succeed.
try to create an app with logo, and see check:
before the fix, the app creation failed with the exception stack as shown in jira ticket comments
after the fix, the app creation pass with no errors …

BB2-486-Create-App-with-Logo-fails

---

templates/include/foot.html

[BB2-503](https://jira.cms.gov/browse/BB2-503)
As a front-end engineer, I want to improve the performance of our web server
Removes Crazy Egg JS lib
* Watch for any JS or dependancy errors
* If the answer to …

BB2-503 Crazy Egg lib was no longer being used.

---

hhs_oauth_server/settings/base.py

[BB2-496](https://jira.cms.gov/browse/BB2-496)
The application has AWS credentials embedded in the configuration - we need to pull these out to make sure the AWS operations will function without them. 
This removes the hardcoded AWS credentials in base.py so that the boto3 library will use the built-in instance role for AWS API calls.  There are two other associated pieces of work:
- Assigning the instance role the same permissions as hardcoded IAM user (done)
- Removing hardcoded credentials from deployment config (https://github.com/CMSgov/bluebutton-web-deployment/pull/1408)
- Password reset emails work
- Logo uploads to S3 work
In my testing in the test environment …

BB2-496: Remove hardcoded AWS credentials in favor of built-in instance role

---

hhs_oauth_server/request_logging.py

[BB2-494](https://jira.cms.gov/browse/BB2-494)
Improve FHIR payload logging to better identify which beneficiaries are getting empty fields.
Also adds elapsed time.
**The following is a list of changes from the commits (including additional comments):**
* Add logging items to request_logging.py
- Add item: elapsed = Response time (end_time - start_time)
- Add item: fhir_element_count = FHIR payload number of top level elements.
- Add item: fhir_resource_id = FHIR payload 'id'.
- Add item: fhir_resource_type = FHIR payload 'resourceType'.
- Add item: fhir_total = FHIR payload 'total'.
- Add item: fhir_bundle_type = FHIR payload 'type'.
* Rename and add logging items.
- Add fhir_entry_count = FHIR entry count in response.
- Rename …

BB2-494 Add FHIR payload items to logging

---

apps/integration_tests/endpoint_schemas.py
apps/integration_tests/integration_test_fhir_resources.py

[BB2-471](https://jira.cms.gov/browse/BB2-471)
As a team, we need to improve our integration testing to include the new V2 test cases so that we can seamlessly test the V2 Integration
A/C
Any testing, manual or otherwise, should be set up as an integration test
JSON Schema - when applicable
Can use this to validate when plausible
FHIR R4 may not work with JSON schema due to size and complexity
This ticket should be done in combination with the existing EOB & integration tests
* TODO
* Add full cycle tests for automated headless run of BB2 testclient auth v1 and v2 through webUI
* Add full cycle tests for user accounts management: create user, create apps, password change …

BB2-471-Improve-Integration-Tests-PR2

---

apps/dot_ext/models.py
apps/dot_ext/tests/test_models.py
apps/logging/loggers.py
apps/logging/management/commands/log_global_state_metrics.py
apps/logging/tests/audit_logger_schemas.py
apps/logging/tests/test_loggers_management_command.py

[BB2-506](https://jira.cms.gov/browse/BB2-506)
As a developer, I want to improve our logging to capture more granular information around beneficiary counts so that we can report out the value to stakeholders
Summary:
This adds some global counts when the `log_global_state_metrics` custom Django management command is called:
* Log type "global_state"
- `real_bene_cnt` - The total number of real beneficiaries in BB2.
- `synth_bene_cnt` - The total number of synthetic beneficiaries in BB2.
- `global_apps_active_cnt` - The total number of active applications in BB2.
- `global_apps_inactive_cnt` - The total number of inactive applications in BB2.
- `global_apps_require_demographic_scopes_count` - The total number of active apps requiring …

BB-506 DASG Metrics - Adding logging to gain count information

---

apps/testclient/views.py
apps/wellknown/views/openid.py

[BB2-595](https://jira.cms.gov/browse/BB2-595)
External Reference: 
[BB2-547](https://jira.cms.gov/browse/BB2-547)
During testing of testclient search result pagination, e.g. page 1/10 - on first page of total 10 pages:
(1) when search bundle contains 0 resources (still has trivial link section), or BFD return an operation outcome of error (see attached iamge), it should show no pagination info
(2) when resource total is a multiple of page size (10), the page total is off, e.g.
when resource total is 370, the pagination displayed as: page 37/38 at last page.
A/C
the pagination info displayed are accurate on corner cases.
(1) for EOB with claims count of K X 10, the pagination info should be Page K/K when on last page
(2) for empty search …

BB2-595-Testclient-PaginationInfo-Inaccurate-On-Edgecases

---

apps/wellknown/views/openid.py

[BB2-603](https://jira.cms.gov/browse/BB2-603)
The OIDC Discovery endpoint response is still showing 'Implicit' as an option. We should remove this from the options.
v1 OIDC Discovery response:
`{
"issuer": "http://localhost:8000",
"authorization_endpoint": "http://localhost:8000/v2/o/authorize/",
"token_endpoint": "http://localhost:8000/v2/o/token/",
"userinfo_endpoint": "http://localhost:8000/v2/connect/userinfo",
"ui_locales_supported": [
"en-US"
],
"service_documentation": "https://bluebutton.cms.gov/developers",
"op_tos_uri": "https://bluebutton.cms.gov/terms",
"grant_types_supported": [
"authorization-code",
"implicit",
"refresh_token"
],
"response_types_supported": [
"code",
"token"
],
"fhir_metadata_uri": …

BB2-603-Remove-Implicit-From-OIDCDiscovery-Response

---

dev-local/msls/main.go
docker-compose.yml

[BB2-608](https://jira.cms.gov/browse/BB2-608)
BB2-544 Added SLSX signout as part of AUTH flow, accordingly MSLSX needs to add a mock sign out service in GO code so that MSLSX will continue to work.
A/C
add func signout to MSLSX go code
MSLSX continue to work as expected
Added signout service to MSLSX go code.
* TODO
* Does this PR modify or invalidate any of our …

BB2-608-Add-signout-to-MSLSX

---

requirements/requirements.dev.txt
requirements/requirements.in
requirements/requirements.txt

[BB2-625](https://jira.cms.gov/browse/BB2-625)
Summary:
Per Snyk scan, BB2 server needs to bump django to 2.2.22 to address a high vulnerability.
CWE-644
CVE-2021-32052
CVSS 7.3 HIGH
SNYK-PYTHON-DJANGO-1290072
details:
`Introduced through
django@2.2.20, django-bootstrap-form@3.4 and others
Fixed in
django@2.2.22, @3.1.10, @3.2.2
Exploit maturity
NO KNOWN EXPLOIT
Show less details 
Detailed paths and remediation
Introduced through: project@0.0.0 › django@2.2.20
Remediation: Upgrade django to version 2.2.22 or 3.1.10 or 3.2.2
Introduced through: project@0.0.0 › django-bootstrap-form@3.4 › django@2.2.20
Remediation: Pin django to version 2.2.22 or 3.1.10 or 3.2.2
Introduced through: project@0.0.0 › django-localflavor@1.6.2 › django@2.2.20 …

BB2-625-Bump-Django-to-2.2.22

---

apps/logging/serializers.py

[BB2-432](https://jira.cms.gov/browse/BB2-432)
Fix SLSX logging serializer for missing auth_token
* TODO
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and …

BB2-432-Fix-JSON-SERIALIZATION-missing-authtoken

---

templates/design_system/authorize_v2.html

[BB2-660](https://jira.cms.gov/browse/BB2-660)
Problem:
Audit found that BB2 Authorization Demographic Info Access Grant form showing medicare 1-800 number with missing digit as shown below:
Need to fix that as below:
it should be 1-800-633-4227 per our auditor.
A/C:
the text in authorize template corrected and deployed to target ENVs.
fix the 800 number in template.
After deployed to target ENV, verify that 800 number is correct. 
* TODO
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in …

BB2-660-FIX-800-phone-num-Access-Grant-Form

---

apps/bb2_tools/admin.py
apps/bb2_tools/models.py

[BB2-653](https://jira.cms.gov/browse/BB2-653)
To support BB2 V2 Roll out, I want to add a view under BB2 Admin BB2-TOOLS where DEV users joined BFDV2Partners group and applications associated with it are shown in a tabular view.
This helps to monitor the users and organizations who participated in V2 testing.
A/C:
The V2 User and Applications view added where below info can be obtained conveniently:
1. User name, email, organization, user type : DEV / BEN, if the user is "V2 Enabled" - i.e. the user is in group BFDV2Partners
2. Applications associated with the user, these apps are able to access V2 FHIR resources
Add a customized User view "V2 Users" in Admin BB2-TOOLS section
the tabular view includes columns: "V2 Enabled" and "Apps" where …

BB2-653-Create-V2-User-Apps-View-in-Admin-BB2-TOOLS

---

apps/integration_tests/integration_test_fhir_resources.py

[BB2-672](https://jira.cms.gov/browse/BB2-672)
BB2 Integration EOB Profiles tests started failing due to that BFD fixed duplicate EOB claims in EOB search, BB2 Integration EOB profiles tests need to make corresponding changes with regard to the asserts on the EOB claims counts.
This is causing PRs failing CI checking.
A/C:
BB2 Integration EOB tests fixed and all integration tests passing.
Fixed EOB profiles tests:
Search with negative ids (claims ids)
Assert counts of EOB claims (pde, inpatient, outpatient, ...) with de-duplicated number
* TODO
* If the answer to any of the questions below is **Yes**, then here's a …

BB2-672-Fix-BB2-Integration-EOB-Profiles-Tests

---

splunk/v2_activities_dashboard.xml

[BB2-651](https://jira.cms.gov/browse/BB2-651)
As BB2 Developer, PM, Stake holder, I want to monitor applications activities accessing BB2 V2 API, e.g.
in the past 7 days, 14 days, 24 hrs etc.:
total v2 requests
counts of FHIR resources queries: Patient, EOB, Coverage
active apps count accessing v2
break down of counts of v2 calls per applications
A/C:
Splunk dashboard created which collect above metrics and stats.
Optional:
A link added to BB2 Admin bb2-tools Splunk Dashboard section.
A splunk dashboard definition created, it can be deployed to CMS BB2 splunk as described in the readme.md:
https://github.com/CMSgov/bluebutton-web-server/blob/jfuqian/BB2-651-Create-V2-Activities-Splunk-Dashboard/splunk/readme.md
If you're reviewing this PR, …

BB2-651-Create-V2-Activities-Splunk-Dashboard

---

apps/health/checks.py
apps/mymedicare_cb/authorization.py

https://jira.cms.gov/browse/BB2-431
BB2 health endpoint timing out before getting a response back from SLSX
This PR adds a 5 second timeout to both the SLSX health endpoint, along with the FHIR health endpoint
* Do you think 5 seconds is too short?
* Do you think it needs any tests, or since its just a healthcheck endpoint, and timeout is a documented feature of the library we can just leave it as is?
* Does this PR add any …

[ BB2-431 ] Adding a 5 second timeout to the external healthcheck endpoints

---

hhs_oauth_server/settings/base.py

[BB2-652](https://jira.cms.gov/browse/BB2-652)
Currently, the splunk dashboard links in BB2 Admin BB2-Tools Splunk Dashboards page are broken due to relocate of cms splunk base URL..
This needs to be fixed so that user can access splunk dashboards:
A/C:
The splunk URL (set in base.py) set to correct value.
and new links added:
Login to BB2 Admin, and go to BB2-TOOLS -> Splunk Dashboards:
(make sure be on CMS VPN required by CMS splunk access)
click each of the links to named splunk dashboards and verify that the corresponding dashboard function as expected.
* TODO
* If the answer to any of the questions below is …

BB2-652-Fix-AdminBB2-Tools-Splunkboards-links

---

apps/logging/tests/audit_logger_schemas.py
apps/mymedicare_cb/loggers.py

[BB2-567](https://jira.cms.gov/browse/BB2-567)
This removes two unneeded log entries related to the merged in PR:  https://github.com/CMSgov/bluebutton-web-server/pull/924
The test related to those log entries was causing the tests to fail when run locally, but were passed via the continuous-integration/jenkins/pr-merge Github check.
These verify_ssl config settings do not need to be logged for each of these events. The values can be gathered in other ways outside of the logging if needed.
**The following is a list of changes from the commits (including additional comments):**
* Remove unneeded logging items
- Remove `sls_verify_ssl_internal` and `sls_verify_ssl_external` items from `log_authenticate_start()` in apps/mymedicare_cb/loggers.py …

BB2-567: Remove unneeded verify_ssl logging items

---

apps/accounts/views/oauth2_profile.py
apps/fhir/bluebutton/loggers.py
apps/fhir/bluebutton/views/generic.py
apps/integration_tests/integration_test_fhir_resources.py
apps/logging/loggers.py

[BB2-661](https://jira.cms.gov/browse/BB2-661)
As BB2 Developer, PM, Stakeholder, it is highly desirable to be able to track v2 usage on PROD/PROD SBX, including detect apps that got blocked by bfd_v2_flag, so that Blue Button API can reach out to them and help with their V2 migration and testing.
Currently a splunk board "V2 Activities Dashboard" is created on SBX, but it is lacking above info, i.e., there is not enough info in current logging to distinguish a 404 error logging caused by bfd_v2_flag from other regular 404 NOT FOUND.
To overcome this:
A logger is added and it will log below info at the point where bfd_v2_flag is checked and 404 raised:
type: v2_blocked
user: the current request's user
app: the current app
timestamp: the …

BB2-661-Add-Logging-for-V2-flag-blocked-fhir-requests

---

requirements/requirements.dev.txt
requirements/requirements.in
requirements/requirements.txt

[BB2-647](https://jira.cms.gov/browse/BB2-647)
As part of routine security audit, we need to upgrade Django to fix vulnerabilities
This simply bumps Django from 2.2.22 to 2.2.24.
N/A
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a …

BB2-647: Upgrade Django to 2.2.24

---

.gitignore

No ticket
Just adding a `dev-tools` directory to the git ignore file. This directory can be used to put any local scripts you create that you don't want checked (most likely ones with credentials in them)
Just adding a `dev-tools` directory to the git ignore file. This directory can be used to put any local scripts you create that you don't want checked (most likely ones with credentials in them)
* TODO
* Does this PR add any …

[ NO-TICKET] Adding a dev tools directory to put scripts you don't want checked in

---

apps/health/checks.py
apps/health/urls.py
apps/health/views.py
apps/integration_tests/integration_test_fhir_resources.py

[BB2-717](https://jira.cms.gov/browse/BB2-717)
In order to separately monitor the availability of BFD and SLS, we should utilize separate endpoints for this instead of running everything from /health/external
Note: We're using /health for load balancers but not /health/external
AC:
Create new endpoint /health/bfd that only runs the BFD health check
Create new endpoint /health/sls that only runs the SLS health check
Create new endpoint /health/db that runs the Django database health check 
Optionally decommission /health/external if not useful anymore
Add a unit test in for every new end point listed above
Note to A/C, instead of unit tests, integration tests added to best cover newly added health check end points
and legacy external end …

BB2-717-Separate-BFD-SLS-healthcheck-into-specific-EPs

---

.github/pull_request_template.md
docker-compose/readme.md

https://jira.cms.gov/browse/BB2-736
As a BB2 developer I want better documentation around running migrations and I want documentation on how to deploy a cherry-picked hotfix should an incident occur and new code be required to fix it.
Added documentation changes for PR templates adding a section about migrations.
Added documentation for how to run migrations locally and how to rollback a migration.
Also added some hotfix documentation to our Incident docs in confluence - I added a comment w/ the link in JIRA.
* Is there anything missing?
* Is it clear/understandable?
* If the answer to any of the questions below is …

[ BB2-736 ] Adding documentation for migrations

---

Jenkinsfiles/Jenkinsfile.cbc-run-multi-pr-checks-w-selenium

[BB2-814](https://jira.cms.gov/browse/BB2-814)
Set the parameter RUN_SELENIUM_TESTS = false
Once merged we can update the Jenkinsfile on CHECK - Github PRs to the new selenium job
* This is the desired default setting for CHECK - Gihub PRs Jenkins job
* N/A
* Does this PR store or transmit data …

[ BB2-814 ] Set selenium test param default to false

---

docker-compose/bluebutton_server_start.sh

[SOMEPROJECT-42](https://jira.cms.gov/browse/SOMEPROJECT-42)
Story:
When start BB2 instance on a dev local environment, a root admin user is created, now that part is broken, i.e., the root user is not created as part of the docker-compose up.
It is due to the env vars name mismatch as shown below:
in .env.sample:
SUPER_USER_NAME=root
SUPER_USER_PASSWORD=blue123
SUPER_USER_EMAIL=bluebutton@example.com
but the super user creation code shown below still refer to user name and etc as a slightly different var names :
echo "from django.contrib.auth.models import User; User.objects.create_superuser('${SUPERUSER_NAME}', '${SUPERUSER_EMAIL}', '${SUPERUSER_PASSWORD}')" | python manage.py shell
AC:
fix the name references in super user creation code …

BB2-Fix-DevLocal-Super-User-Creation

---

apps/testclient/templates/home.html

[BB2-1002](https://jira.cms.gov/browse/bb2-1002)
it is noticed that there are duplicate words in testclient home page
the dup word 'allows' removed
*
* Does this PR add any new software dependencies? **No**
* Does this PR modify or invalidate any of our security controls? **No**
* Does this PR store or transmit data that was not stored or transmitted before? **No**
* If the answer to any of the questions below is **Yes**, …

Removed duplicate word

---

apps/creds/templates/get_creds.html
apps/creds/utils.py
apps/creds/views.py

[BB2-975](https://jira.cms.gov/browse/BB2-975)
[BB2-976](https://jira.cms.gov/browse/BB2-976)
[BB2-978](https://jira.cms.gov/browse/BB2-978)
Implementation of PROD credentialing request models and functions as part of the PROD credentialing automation effort.
AC:
Create table for housing prod credentialing requests
Make sure to get team feedback early on this piece, so that we know the table has the fields we will need it to have
Needs to have a field for when the credential creation page will expire (5 minutes after generation)
Needs to have a counter for the number of times the credential page has been used
Needs to have a FK to the associated application that it was generated for
Create a function for generating a unique url for a row …

[BB2-975] Fix creds delivery template "fetch" and "download" generated URI issue

---

hhs_oauth_server/request_logging.py

[BB2-1099](https://jira.cms.gov/browse/BB2-1099)
Fix bug with `resp_access_token_hash` log item in hhs_oauth_server/request_logging.py
This was logging the same hash value for a None value every time.
**The following is a summary of the files in this PR**
* Are there any unhandled and/or untested edge cases you can think of?
* Does this make any backwards-incompatible changes that might break end user clients?
* Can you find any bugs if you run the code locally and test it manually?
* Naming in general? Do the namings of variables, methods, classes, and other items make sense? Are they too verbose, or not verbose enough? Any redundancies? Are the comments descriptive …

[ BB2-1099 ] Fix bug with resp_access_token_hash log item

---

Dockerfile.selenium

[BB2-1098](https://jira.cms.gov/browse/BB2-1098)
BB2 Selenium tests docker build is broken, the docker compose building process crashed when installing Pillow.
Bump the Pillow version in Dockerfile to match the requirements.dev.txt, this will bring us up to v 9.0.0.
If you would like to confirm, just test locally with this branch to make sure Selenium tests are running without error.
Steps to repeat:
1. Check out bb2 web server to local repo
2. Do the usual local dev set up:
2.1 cp .env.example .env
2.2 source ./docker-compose/source_env_secrets_from_keybase.sh
3. ./docker-compose/run_selenium_tests_local_keybase.sh
You should see a successful run, I performed local tests and confirmed it is working now. Here is the test results I saw after …

[ BB2-1098 ] BB2 Selenium tests docker build broken

---

requirements/requirements.dev.txt
requirements/requirements.in
requirements/requirements.txt

[BB2-1222](https://jira.cms.gov/browse/BB2-1222)
Summary:
This resolves a vulnerability alert from Snyk this morning.
INFO:
How to fix?
Upgrade [Django](https://pypi.org/project/Django/) to version 2.2.28, 3.2.13, 4.0.4 or higher.
Overview
Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Affected versions of this package are vulnerable to SQL Injection via QuerySet.explain(**options) in option names, using a suitably crafted dictionary, with dictionary expansion, as the **options argument on PostgreSQL.
* TODO
* If the answer to any of the questions below is …

[BB2-1222] Bump Django to 2.2.28 to Mediate CVE-2022-28346 and CVE-2022-28347

---

apps/integration_tests/integration_test_fhir_resources.py

[BB2-1262](https://jira.cms.gov/browse/BB2-1262)
Context:
BB2 server integration tests failed, see test failure error:
FAIL: test_fhir_meta_endpoint_v2 (apps.integration_tests.integration_test_fhir_resources.IntegrationTestFhirA
piResources)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django/test/utils.py", line 373, in inner
return func(*args, **kwargs)
File "/code/apps/integration_tests/integration_test_fhir_resources.py", line 290, in test_fhir_meta_endpoin
t_v2
self._call_fhir_meta_endpoint(True)
File "/code/apps/integration_tests/integration_test_fhir_resources.py", line 312, in _call_fhir_meta_endpoi
nt
self.assertEqual(fhir_ver, …

[BB2-1262] Fix integration tests assert on FHIR version 4.0.0

---

apps/integration_tests/integration_test_fhir_resources.py
docker-compose/readme.md
templates/email/email-common-get-started-template.html
templates/email/email-common-get-started-template.txt
templates/email/email-success-first-api-call-template.html
templates/email/email-success-first-api-call-template.txt

[BB2-1241](https://jira.cms.gov/browse/BB2-1241)
[BB2-1264](https://jira.cms.gov/browse/BB2-1264)
BB2-1241: The footer in the BB2 Sandbox Automated Emails has a broken link: "Get Started with our Sample Apps" section of the email footer. It needs to be updated with the correct link.
BB2-1264: the link in 1st API call email: "Read More " 
Here is a screenshot of the email:
!Screen Shot 2022-04-13 at 11.35.09 AM.png|width=333,height=476!
The error message that shows when the link is clicked. The bad link: https://bluebutton.cms.gov/blog/More-Sample-Applications.html
Similar broken links also found in github repo dev local readme.md at below location:
https://github.com/CMSgov/bluebutton-web-server/tree/master/docker-compose/readme.md
the mark …

[BB2-1241, BB2-1264] SBX automated email and dev local readme broken links

---

apps/creds/admin.py

[BB2-1137](https://jira.cms.gov/browse/BB2-1137)
Context:
The newly introduced PROD App Credentialing Request Generation, and Lookup and Delete Django Admin pages are very slow, even with a few creds requests records, the cause is that a filter on user name is added which will trigger a table join with User table, the user table also include BENE type users which are in large number tens of thousands on PROD, SBX.
the solution is to remove the filter on user name, since app name is unique, and filter on app name provides sufficient look up functionality.
AC:
Verify that with the fix, the creds delivery operations are fast.
Removed user name filter on creds admin view, which speed up the creds requests operations significantly.
Note, BB2 …

[BB2-1137] Fix PROD App Credential Delivery Tool (Django Admin) Slowness

---

hhs_oauth_server/request_logging.py

[BB2-1316](https://jira.cms.gov/browse/BB2-1316)
Add BB2 app server logging of SDK header
This ticket adds logging from sdk headers to allow us to collect usage analytics.
Companion tickets [BB2-1322](https://jira.cms.gov/browse/BB2-1322) and [BB2-1323](https://jira.cms.gov/browse/BB2-1323) added the data to the request headers.
* When deployed, check to ensure you are getting the logging info from node and python SDKs.
No security implications.
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document …

BB2-1316 Add BB2 app server logging of SDK header

---

hhs_oauth_server/urls.py

[BB2-1402](https://jira.cms.gov/browse/BB2-1402)
avoid page render issues on django-admin site
Set admin.site.enable_nav_sidebar to False
* Please click around some links with django-admin and make sure all views look normal.
* Does this PR modify or invalidate any of our security controls? No**.
* Does this PR store or transmit data that was not stored or transmitted …

[ BB2-1402 ] set admin sidebar to False

---

splunk/api_big_stats_dashboard.xml
splunk/authorization_flow_dashboard.xml
splunk/dasg_metrics_dashboard.xml

[BB2-1509](https://jira.cms.gov/browse/BB2-1509)
Update the dashboards in Splunk to exclude the "TestApp" and other internal apps.
* Make sure that the internal apps are properly filtered in Splunk.
* If the …

BB2-1509 update splunk to filter out internal apps.

---

apps/dot_ext/tests/test_views.py
apps/dot_ext/views/authorization.py

[BB2-1482](https://jira.cms.gov/browse/BB2-1482)
Per a review of our logging using Splunk, we found that some 3rd party applications are in-correctly including their CLIENT_SECRET in HTTP query parameters. This presents a potential security issue and is not a best practice. For example, the secret value will show up in BB2 and 3rd party logging.
We need to allow custom 3rd party parameters to be passed in some cases, so we would not be able to restrict parameters to just the ones needed. We can check if the query parameters include the client_secret and produce an error if so. This would help to prevent sandbox developers from doing this in their code—prior to moving to production.
AC:
Review and catalog API end points where query parameters …

[BB2-1482] Restrict use of CLIENT_SECRET as query parameter on API requests from Apps

---

apps/accounts/models.py

[BB2-1646](https://jira.cms.gov/browse/BB2-1646)
When I first [created a sandbox account](https://sandbox.bluebutton.cms.gov/v1/accounts/create), I got the "verify your blue button 2.0 developer sandbox account" email as expected.
After I verified my email, I got the "verify your blue button 2.0 developer sandbox account" email again, and it was exactly the same as the first. It should have been Get started with Blue Button 2.0 according to this [list of automated emails](https://confluence.cms.gov/x/cs48Iw).
===
This will become a higher priority when we update the intended content of the "verify your blue button 2.0 developer sandbox account" email to remove the links to documentation and other resources from it, per …

[BB2-1646] New sandbox users receive incorrect automated email after verifying account

---

apps/accounts/tests/test_create_account.py
apps/logging/request_logger.py
apps/logging/tests/test_audit_loggers.py
apps/logging/tests/test_loggers_management_command.py
apps/logging/utils.py
apps/mymedicare_cb/tests/test_callback_slsx.py
apps/test.py

[BB2-1646](https://jira.cms.gov/browse/BB2-1646)
Use this PR to add unit tests for BB2-1646
Existing account creation tests extended to verify correct email notifications are sent.
Add unit tests for BB2-1646 which is already in master.
1. Just run the unittests locally and verify all tests pass
2. Review changes to the tests - make sure it does test the email notification for the account creation process
* TODO
* Does this …

[BB2-1646] SBX users receive incorrect automated email after verify account - add unit tests

---

apps/fhir/bluebutton/views/generic.py
apps/fhir/server/authentication.py

[BB2-1544](https://jira.cms.gov/browse/BB2-1544)
Context:
Cardinal Health registered their app with name :
Cardinal Health\u2122 Care Exchange - QA
where unicode \u2122 is the trade mark char (as described below), that is causing problem in BB2 authorization flow processing.
The symbol for a registered trademark is "circled R registered sign" or 174 in both ISO/Latin-1 (8859/1) and ISO 10646. In UTF-8 it has the following two-byte encoding: 0xC2, 0xAE. Here's a rough idea of how that's generated: ®, the registered trademark symbol, HTML &#174
It is reasonable and good practice to restrict the app name to only use printable characters from ASCII characters from 0-127.
Or even safer, restrict app name to use only A-Z, a-z, 0-9, space, dash, …

[BB2-1544] Fix header value (BlueButton-Application) encoding error on data request

---

apps/integration_tests/selenium_cases.py
apps/integration_tests/selenium_tests.py
docker-compose.selenium.remote.yml
docker-compose/readme.md
docker-compose/run_selenium_tests_local.sh
docker-compose/run_selenium_tests_remote.sh

[BB2-1595](https://jira.cms.gov/browse/BB2-1595)
Context:
To automate BB2 post deployment smoke tests, a selenium test suite can be created with TEST/SBX/PROD as the targeted BB2 server.
Currently, there are selenium tests leveraging BB2 built-in testclient where authorization flow and data flow are comprehensively covered, but the BB2 server used is a local instance.
AC:
the existing selenium tests re-factored such that it can also be set up to run against a remote BB2 server - e.g. TEST, SBX, PROD.
Added docker compose and script to run existing bb2 server selenium tests against a remote BB2 server, e.g. BB2 on PROD, SBX, or TEST
Note, existing BB2 selenium tests are running against a local BB2 server - this is usually testing some dev …

[BB2-1595] Add Selenium Tests Targeted At BB2 ENVs (On Remote EC2)

---

apps/dot_ext/forms.py
apps/dot_ext/tests/test_form_application.py

[BB2-1666](https://jira.cms.gov/browse/BB2-1666)
Our application names should contain just "safe" ASCII characters to prevent possible issues with 3rd party libraries and external reporting systems such as Splunk.
For example, Splunk has trouble with the non ASCII type naming. When reviewing our Splunk dashboards and performing searches, there are NO search results for Cardinal health with the TM in the search string. It gets zero results on the dashboards when using the pull-down for selecting the application. Also not able to get results unless replacing the TM with a wildcard "*".  Other external systems may have issues with the naming like:  Medicare-gov, New Relic, Insights.
We should restrict our application naming to prevent current …

[BB2-1666] VALIDATE: Restrict new App Name To printable ASCII subset

---

apps/fhir/bluebutton/utils.py

[BB2-1726](https://jira.cms.gov/browse/BB2-1726)
Update headers to add missing properties BFD wanted back.
* Make sure header info has all data.
* If the answer to any of the questions below is **Yes**, then …

BB2-1726 update headers for BFD

---

Dockerfile.selenium

[BB2-1886](https://jira.cms.gov/browse/BB2-1886)
Description:
BB2 server dependent package Pillow has been updated to 9.3.0 to mediate vulnerabilities, however, the Dockerfile.selenium (used for running selenium tests) still pip install Pillow=9.0.1, this will lead to selenium tests docker compose run fail.
TODO:
Fix the Dockerfile.selenium as below:
pip install Pillow==9.3.0
AC:
The docker compose for selenium tests can be run as expected
Change the Pillow version in Dockerfile.selenium from 9.0.1 t0 9.3.0
1. Verify that the Pillow version in Dockerfile.selenium changed from 9.0.1 t0 9.3.0
2. Verify the updated Docker for selenium tests work as expected:
2.1 selenium tests (local bb2 instance) passing: run …

[BB2-1886] Dev local selenium tests Dockerfile: bump Pillow version to 9.3.0

---

apps/home/templates/authenticated-home.html

[BB2-1964](https://jira.cms.gov/browse/BB2-1964)
Description:
Currently, at BB2 Developer Dashboard Add Application web UI the button with text label "Add an Application" not visible because the text label (text color is the same as the background color), to show the text, you need to mouse hovering the button.
This cosmetic behavior is actually introduced during the US gov banner change where new CSS have applied to the button "Add an Application".
See screen shots for the behaviors:
No mouse over the button:
Mouse hovering the button:
TODO:
locally override the css to correct the button
AC:
The "Add an Application" button has the desirable responsive design :
i.e. Showing blue background with white text "Add an Application" when no mouse …

[BB2-1964] Fix CSS for BB2 Developer Dashboard Add an Application Button

---

apps/core/management/commands/create_test_feature_switches.py
apps/testclient/management/commands/create_test_user_and_application.py

[BB2-2006](https://jira.cms.gov/browse/BB2-2006)
Context:
With the up coming data access limit feature, it is time to choose the "data access type" for the BB2 built-in TestApp (deployed on PROD / SBX / TEST), currently the default would be "ONE_TIME" and that would not work well with the purpose of TestApp usages.
A proper type needs to be decided (SPIKE) which should cause minimum impact on all existing tests suites (e.g. BB2 selenium tests) and test tools (e.g. BB2 testclient webUI) OR ideally no impact after the feature deployed and publicly available.
This has to be done before the feature release.
One good candidate for the BB2 built-in TestApp's data access type would be:
RESEARCH_STUDY with expiration date: 12/31/9999
AC:
Research …

[BB2-2006] SPIKE Choose data access type for the BB2 TestApp (built-in)

---

apps/authorization/tests/test_data_access_grant_permissions.py
apps/integration_tests/integration_test_fhir_resources.py
hhs_oauth_server/settings/base.py

[BB2-1949](https://jira.cms.gov/browse/BB2-1949)
This updates our error messages related to the data access limit work.
Are the messages correct and matching those proposed in the Jira story?
- If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
- Does this PR add any new software dependencies? **No**.
- Does this PR modify or invalidate any of our security controls? **No**.
- Does this PR store or transmit data that was not stored or transmitted before? **No**.
- If the answer to any of the questions below is **Yes**, then please add StewGoin as a …

[ BB2-1949 ] Update data access limit error messages

---

apps/authorization/models.py
apps/authorization/tests/test_data_access_grant.py
apps/authorization/tests/test_data_access_grant_permissions.py
apps/core/models.py
apps/dot_ext/admin.py
apps/dot_ext/models.py
apps/dot_ext/tests/test_models.py
apps/dot_ext/utils.py
apps/test.py

[BB2-1957](https://jira.cms.gov/browse/BB2-1957)
Convert the access data grant switch to a flag so the access grant feature can be turned on by application.  We needed a flag by app to allows us to turn on the access grant code for specific applications/users.  It is needed for beta testing.
* Check out the application and data access grant models and make sure they make sense.
* Check that all tests are passing.
* Create the flag in django admin and add a user and make sure that the user has the data access flag turned on for them.
* If the answer to any of the questions below is **Yes**, then here's a link to the …

BB2-1957 Change data access switch to flag.

---

Dockerfile.selenium
apps/integration_tests/selenium_cases.py

[BB2-2193](https://jira.cms.gov/browse/BB2-2193)
medicare.gov login page has been re-designed, and this PR includes changes needed to passing all the tests as required by the AC
Note that it turns out that the new login page does not break BB2 selenium tests, the changes made here are actually maintenance  changes needed to make all selenium tests passing.
1. Fix newrelic version in selenium Dockerfile
2. Change the synthetic bene used for selenium tests from BBUser29001 to BBUser00000, due to BBUser29001 ran into update password dialog at medicare.gov login.
* TODO
* If the answer to any of the questions below is …

[BB2-2193] Test BB2 with new medicare login page

---

scripts/medicare-test-synth-logins/README.md
scripts/medicare-test-synth-logins/setup_venv.sh
scripts/medicare-test-synth-logins/test_medicare_logins.py

[BB2-2230](https://jira.cms.gov/browse/BB2-2230)
This creates a login tester tool for medicare sythetic patient accounts. This can be used to validate logins across sets of accounts and report on issues.
We are looking to run this periodically via a Jenkins CBC project.
The following is a summary of the added files:
- `scripts/medicare-test-synth-logins/setup_venv.sh`:
- Script used to setup a Python virtual enviornment at `/tmp/venv_python`.
- This is sourced prior to running the tool.
- `scripts/medicare-test-synth-logins/test_medicare_logins.py`:
- Python tester tool.
- See README.md for usage instructions.
- `scripts/medicare-test-synth-logins/README.md`:
- README documentation about the tool and its usage.
- Try out the tool locally.
- …

[ BB2-2230 ] Medicare synthetic accounts login tester

---

requirements/requirements.dev.txt
requirements/requirements.in
requirements/requirements.txt

[BB2-2361](https://jira.cms.gov/browse/BB2-2361)
Django 3.2.19 fixes a security issue with severity “low” in 3.2.18.
***UPDATE***
After pushing PR a new issue came up and we are now moving to 3.2.20
Updates to Django 3.2.20
* verify app passes all tests
* If the answer to any of …

BB2-2361 Bump django version to 3.2.19 to address vulerability

---

apps/dot_ext/views/authorization.py

[BB2-2522](https://jira.cms.gov/browse/BB2-2522)
Change from switch to flag that can select by application
This PR removes the need for the "new_auth" waffle switch and instead uses the existing flag "limit_data_access".
The intention of this switch is to make available the new permissions screen to beta testers using the flag and allow other users to continue using the older screen.
Reviewers should insure that they can see the appropriate permissions screen when go through the authorization flow.
The older screen will be shown if the application developer has NOT been added to the flag users property.  
i.e. If using the test client, test by logging into the appropriate django-admin and finding the TestApp application in the list of …

BB2-2522 Change flag to switch for permissions screen

---

hhs_oauth_server/request_logging.py

[BB2-2644](https://jira.cms.gov/browse/BB2-2644)
Add logging of requests that come from our sample client
Add new values to request_logging.py.  This is to capture metrics surrounding which products are being used by 3rd party devs.
* Try making some requests from each sample app to verify that the correct application is properly logged.
* NOTE: These values will not be available until BB2-2501 is also done.  You will need to be sure that you have that code locally for your sample client before these logs can be captured.
* If the answer to any of the questions below is **Yes**, then here's a link to the associated …

BB2-2644 Add new sample client header values to request logging.

---

requirements/requirements.dev.txt
requirements/requirements.in
requirements/requirements.txt

[BB2-2674](https://jira.cms.gov/browse/BB2-2674)
This bumps the Django package version to 3.2.21 to address a reported SNYK vulnerability.
Updates the Django package from version 3.2.20 to 3.2.21.
- If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
- Does this PR add any new software dependencies? **No**.
- Does this PR modify or invalidate any of our security controls? **No**.
- Does this PR store or transmit data that was not stored or transmitted before? **No**.
- If the answer to any of the questions below is **Yes**, then please add StewGoin …

BB2-2674 Update Django package version to 3.2.21

---

apps/dot_ext/tests/test_authorization.py
apps/dot_ext/utils.py

[BB2-2759](https://jira.cms.gov/browse/BB2-2759)
This PR update the validate_app_is_active check to work with both the auth headers and the request data.  Initially this method only used POST/GET data to locate the application.  It now will also check the headers to retrieve the application before testing the active flag.  In one case, the calling code requires the application to be returned from this method as well so that was left as is.  We should consider refactoring that as well to make the code more readable.
* Test going through the auth flow using, cURL and/or postman as well as through the test client or one of the example applications.
Submitters should complete …

BB2-2759 update token endpoint to work with auth headers

---

apps/logging/loggers.py
apps/logging/tests/audit_logger_schemas.py
apps/logging/tests/test_loggers_management_command.py

[Blue Button 2.0](https://jira.cms.gov/browse/BB2-2830)
Adds data access info into global metrics logger to be able to view in Quicksight.
* What should the default value of limit_data_access be if flag is not on (None or False)
* Does this PR store or transmit data that was not stored or …

BB2-2830 Enable data access grant info in quicksight

---

apps/testclient/management/commands/create_test_users_and_applications_batch.py
docker-compose/readme.md

[BB2-2863](https://jira.cms.gov/browse/BB2-2863)
This change adds token options to the Django command that creates test users and applications.
* Add token options
* Add function to start user numbering not at 0 if existing generated users exist
* Move token scope save to token helper function
* Fixes in case 0 is passed for application option
* Skips .rif entries that have already been added
* Some things were moved around, if they don't make sense, feel free to comment.
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security …

BB2-2863 Add token options to Django batch creation command

---

apps/dot_ext/forms.py
apps/dot_ext/models.py
apps/dot_ext/templates/oauth2_provider/application_detail.html
apps/dot_ext/tests/test_beneficiary_demographic_scope_changes.py
apps/mymedicare_cb/tests/test_callback_slsx.py
templates/include/app-form-required-info.html

[BB2-2868](https://jira.cms.gov/browse/BB2-2868)
The Sandbox app details form contains a typo in the question about demographic information. "Beneficiary" is misspelled "beneficary"
Change all instances of "beneficary" to "beneficiary" in the repo.
* That changes to text do not affect functionality.
* Does this PR modify or invalidate any of our security controls? …

BB2-2868 Change all instances of "benificary" to "beneficiary"

---

apps/dot_ext/models.py
apps/dot_ext/tests/test_models.py

[BB2-2893](https://jira.cms.gov/browse/BB2-2893)
When an application changes its access grant category, we do not want to change its existing access grants.
The migration script can be run to do this as a more deliberate action.
Leaves existing data access grants unchanged when an application is saved
and the data access type is changed.
* I'm logging the data access type change regardless of waffle flag assuming we still want to log this after the feature is fully rolled out
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security …

BB2-2893 Update application save to preserve access grants

---

apps/dot_ext/models.py
apps/dot_ext/views/authorization.py
templates/design_system/new_authorize_v2.html

* Add localization so that date format changes when language is Spanish
[BB2-2874](https://jira.cms.gov/browse/BB2-2874)
Adds Django localization support to access end date on new authorization screen.
* Ensure the new authorization screen without localization looks ok.
* Does this PR add any new software dependencies?  **No**.
* Does this PR store or …

BB2-2874 Add localization to access end date format

---

apps/authorization/tests/test_data_access_grant_permissions.py
apps/dot_ext/tests/test_authorization.py
apps/dot_ext/utils.py
apps/dot_ext/views/authorization.py

[BB2-2935](https://jira.cms.gov/browse/BB2-2935)
From an application's standpoint, it may be confusing that token refreshes are allowed on expired 13-month grants, but then using the tokens received would result in an HTTP 401 when used for a FHIR API request. We'd like to disallow the token refreshes on expired 13-month access grants to avoid this confusion.
This PR changes how the validate_app function gets the user when refresh_token is called.  Instead of relying on the request, we now get the user from the refresh token.  This will give us a more stable process as the token must always be present for a refresh to occur.
Upon study, it was not clear if 400 or 401 should be returned.  However, I decided to use the Oauth exception …

BB2-2935 Disallow token refreshes on expired 13-month access grants

---

apps/authorization/tests/test_data_access_grant_permissions.py
apps/creds/tests/test_credentials_request.py

[BB2-2731](https://jira.cms.gov/browse/BB2-2731)
The credentialing feature does not have test coverage. This story is to provide test coverage for this feature.
Added tests under apps/creds/tests that 
- Test the linked page id/secret results. Also test the downloaded JSON option.
- Test that the link expires.
- Test that the UUID has he correct length
- Test when a credentialing request is not found
- Test that re-fetch/re-download is not allowed
I'm new to working with Django so watch out for convention/style issues and point out if there are better ways of testing the content of the template. Also, let me know if they're are additional test cases that I am not …

BB2-2731: Add tests for credentialing link feature

---

apps/integration_tests/selenium_cases.py
apps/integration_tests/selenium_generic.py
apps/integration_tests/selenium_spanish_tests.py
apps/testclient/management/commands/create_test_user_and_application.py
templates/auth_base.html
templates/design_system/new_authorize_v2.html

[BB2-2918](https://jira.cms.gov/browse/BB2-2918)
Add automated tests for language translation.
Adds a new Selenium test for testing the language link and ensuring language and date format change accordingly.
* Changes TestApp to THIRTEEN_MONTH because this is now the default for new apps and also we cannot check the date format without an end date on access grants.
* …

BB2-2918 Add selenium spanish tests

---

apps/testclient/management/commands/create_test_users_and_applications_batch.py
docker-compose/readme.md

[BB2-2903](https://jira.cms.gov/browse/BB2-2903)
Add archived access grant option to script that generates test objects in the local database.
Adds archived access grant option to test script.
* Readme is correct and print output exists
* Does this PR store or transmit data that was not stored or …

BB2-2903 Create archived access grants in test script

---

apps/fhir/server/authentication.py
apps/health/tests/test_healthchecks.py
apps/health/views.py

[BB2-3057](https://jira.cms.gov/browse/BB2-3057)
Through code scan there were three possible places where tracebacks are bubbled up to the end user.
We'd like to eliminate these from public view while maintaining the traceback in logging.
* Change end user error messages to only list non-code related messages
* Add unit test for any coverage not already covered.
* 
* …

Eliminate possible public tracebacks

---

hhs_oauth_server/settings/base.py

[BB2-2626](https://jira.cms.gov/browse/BB2-2626)
CSRF cookie is not marked secure on the login form of our web server environment sites.
Adds Django setting so that the CSRF cookies are secure in all BB2 environments.
* Does this PR store or transmit data that was not stored or transmitted …

BB2-2626 Make csrf cookie secure

---

docker-compose/readme.md

[BB2-3162](https://jira.cms.gov/browse/BB2-3162)
As a developer of BB2, I would like to be able to set breakpoints to debug tests and local BB2 environments.
Updated Readme for steps related to debugging using visual studio code
* TODO
* Does this PR add any new software dependencies? **Yes** or **No**.
* Does this PR modify or invalidate any of our security controls? **Yes** or **No**.
* Does this PR store or transmit data …

BB2-3162: Add steps to debug and apply breakpoints in visual studio code

---

apps/authorization/models.py
apps/dot_ext/models.py
apps/dot_ext/views/authorization.py
apps/logging/loggers.py
docker-compose/readme.md

[BB2-3229](https://jira.cms.gov/browse/BB2-3229)
As a BB2 developer, I want to deprecate the access grant feature flag in sandbox, but NOT prod.
Make the data access grant feature flag respect the "rollout" option to allow us to enable the feature for all users via Django admin console.
* `docker-compose --profile slsx up --build -d`
* Create a superuser if one doesn't exist (exec into running container and `./manage.py createsuperuser`)
* Log into Django with super user at http://localhost:8000/admin
* Go to http://localhost:8000/admin/core/flag/1/change/
* Check the `Rollout` option
* Log out of Django
* Use the testclient to authenticate with medicare.gov. You should …

BB2-3229: Added rollout logic for access grant feature flag

---

apps/accounts/tests/test_password_reset_while_authenticated.py
apps/accounts/validators.py
apps/accounts/views/login.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/settings/test.py

[BB2-3273](https://jira.cms.gov/browse/BB2-3273)
As a BB2 Production Sandbox User, I want the BB2 team to remove or change the password expiration to once every 365 days so that the BB2 Prod-Sbx user accounts are compliant with the Updated CMS ARS5.1 and NIST800-63B.
Removes password expiration and all related validation and testing.
* Updated tests should provide the best validation by setting the tested date artificially 90 days in the future, 30 days beyond the previous password expiration time.
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact …

BB2-3273: Removed password expirations

---

apps/authorization/views.py
apps/dot_ext/tests/test_views.py

[BB2-3256](https://jira.cms.gov/browse/BB2-3256)
Include Only apps with active DAG in /v1/o/tokens endpoint response (for medicare.gov "connected apps" page)
Updates queryset for auth grants returned by the /tokens endpoint for the medicare.org Connected Apps view.
* Finding a way to test this manually would be great! As is, the unit test in apps.dot_ext.tests.test_views.TestTokenView is the only good test.
* Does this PR add …

BB2-3256: Updated queryset for auth grants

---

README.md
apps/accounts/forms.py
apps/accounts/validators.py
templates/include/app-form-required-info.html

[BB2-3281](https://jira.cms.gov/browse/BB2-3281)
Following [BB2-1651](https://jira.cms.gov/browse/BB2-1651), we determined the need to expose validation rules for passwords and callback URLs.
We should do this in a static fashion.
Locally, http://localhost:8000/v1/o/applications/register/ should display help text below the callback urls text area. Additionally, the signup page will need to be validated upon sandbox deployment (local client invokes sandbox for signups, making it difficult to test locally without a test deplyment). You can validate the added help_text field in accounts/forms.py against existing PW validation rules.
Please indicate if this PR does any of the following:  
* Adds any new …

Added static FE rules for passowrds and url validations

---

apps/authorization/tests/test_serializers.py
apps/authorization/views.py

[BB2-3312](https://jira.cms.gov/browse/BB2-3312)
Update ApplicationSerializer to swap support email for contacts without changing field names. This is necessary because we always expect to see the value in the support_email field where data from this serializer is utilized.
You won't be able to live demo this on the medicare.gov site, so note that the new serializer test passes and that existing tests implementing the endpoint (apps.dot_ext.tests.test_views.TestTokenView) still pass. These tests never checked real emails, but it does validate that the response when support_email is empty is an empty string rather than None. That behavior is shown to be consistent by this test.
Unit tests pass and …

BB2-3312: Updated ApplicationSerializer to swap support email for contacts.

---

apps/docs/templates/openapi.html
hhs_oauth_server/settings/base.py
static/oauth2-redirect.html
static/openapi.yaml

[BB2-3139](https://jira.cms.gov/browse/BB2-3139)
Here we are allowing oauth2 flow using swagger docs.
This change does not use oaut2-redirect.html after authorization. This is because of CORS context has been lost and 
this file will not have values required (as window.opener is null). window.opener looses context if parent and child tabs are not of same domain. 
- Added custom redirect flow in static/oauth2-redirect.html
- Updated openapi yaml path to static/openapi.yaml. Previous path was incorrect.
**Note:**  In order for this to work, one has to update their application and put `https://sandbox.bluebutton.cms.gov/static/oauth2-redirect.html` in **Callback URLS / Redirect Uris** section
**Note**: This flow will not re-populate client id, secret and scopes in authorize …

BB2-3139: Added oauth2 flow to swagger docs

---

apps/dot_ext/views/authorization.py

[BB2-3489](https://jira.cms.gov/browse/BB2-3489)
This PR removes the [Object object] errors when invalid scopes are defined in testing. This issue is funny because DOT tries to return an Oauth-style redirect like
```
{'headers': {'Content-Type': 'text/html; charset=utf-8', 'Location': 'https://oauth.pstmn.io/v1/callback?error=invalid_scope'}, '_charset': None, '_resource_closers': [], '_handler_class': None, 'cookies': <SimpleCookie: >, 'closed': False, '_reason_phrase': None, '_container': ["b''"], 'allowed_schemes': ['https', 'http']}
```
This could be OK, but the usage context of our API makes it unlikely that this kind of response is ever useful. The error is most likely to occur in test and the most likely people to see it are not the end users of our API, but our …

BB2-3489: Remove [Object object] errors

---

hhs_oauth_server/urls.py
hhs_oauth_server/views.py
templates/testobject.html

[BB2-3583](https://jira.cms.gov/browse/BB2-3583)
This adds the akamai test object at /akamai/testobject. This improves the performance of the Akamai edge.
No real complexities, but it needs to be manually reviewed following the below instructions.
You should be able to request the test object by making a GET request to localhost:8000/akamai/testobject in browser, in Postman, or with cURL. You should see a lorem ipsum page.
etc)

BB2-3583: Added akamai sureroute object

---

docker-compose/readme.md

[BB2-3552](https://jira.cms.gov/browse/BB2-3552)
Add instructions for debugging single unit test by setting breakpoints
See instructions in Readme
etc)

BB2-3552: Add instructions for debugging single unit test by setting breakpoints

---

apps/accounts/admin.py

[BB2-3528](https://jira.cms.gov/browse/BB2-3528)
This PR adds a super user column to sort and filter super users in Django Admin
Run the application locally and navigate to http://localhost:8000/admin/auth/user/. You should see a new Superuser Status column with true and false values like the staff status column.
etc)

BB2-3528: Add superuser sort column

---

apps/dot_ext/admin.py
apps/dot_ext/csv.py
apps/dot_ext/fixtures/internal_application_labels.json

[BB2-3401](https://jira.cms.gov/browse/BB2-3401)
This PR allows for application internal labels to be filtered and exported from the My Applications view. Additionally, it removes several fields we don't want exported to csv from the Application export feature.
- Is there a better way to export the internal category? As is, it will look something like `<QuerySet [<InternalApplicationLabels: Personal health record>, <InternalApplicationLabels: Data sharing>]>` in the resulting CSV. The information is there, but it's a little messy.
Run locally, and test setting application internal labels and then testing the filters and the export on http://localhost:8000/admin/bluebutton/myapplication.
Please …

Include internal category in applications filter and limit exported fields

---

splunk/api_big_stats_dashboard.xml

[BB2-3784](https://jira.cms.gov/browse/BB2-3784)
Adds a splunk panel that includes a more inclusive result code query. This can be compared with other similar queries over the same timeframe to identify errors that may otherwise slip through the cracks of our more specific queries. On its own, it's not super useful, but comparing the table to the other result code over time frame charts should help pinpoint things that may otherwise escape us.
Nothing. Just check the Splunk dashboard changes and make sure they make sense.
Sanity check the API Big Stats Dashboard. In particular, the last new panel.
* Any …

BB2-3784: Added inclusive result codes panel.

---

static/openapi.yaml

[BB2-3610](https://jira.cms.gov/browse/BB2-3610)
This PR adds the ability to request V2 scopes via the swagger doc authentication. Additionally, it documents the smart-configuration endpoints and cleans up some of the openid configuration in the openapi.yml file.
Look for typos, sensible descriptions, etc.
Copy/paste the file into the [Swagger editor](https://editor.swagger.io/) in the browser to see the changes.
etc)

BB2-3610: Swagger doc updates for Smart App Launch

---

apps/dot_ext/templates/oauth2_provider/application_detail.html
templates/design_system/authorize_v2.html
templates/include/app-form-required-info.html

[BB2-3844]https://jira.cms.gov/browse/BB2-3844
Changes verbiage to sex instead of gender
Missed verbiage change spots
Verified with local run that changes appear
etc)

Updates to user admin forms

---

requirements/requirements.dev.txt
requirements/requirements.in
requirements/requirements.txt

[BB2-3833](https://jira.cms.gov/browse/BB2-3833)
Upgrades Django
Any breaking tests/functionality
Django version updated properly
Ran through local auth process and was able to get auth token. Also ran through all requests in Postman
etc)

upgrading django to 4.2.20

---

templates/bene_404.html

Unticketed
This PR edits the message in the bene not found scenarios to discourage users from sending sensitive information over email.
Test that the formatting makes sense
Try to use a local test client with a user that doesn't exist in BFD.
etc)

Update bene not found messaging

---

apps/testclient/templates/home.html

[BB2-XXXX](https://jira.cms.gov/browse/BB2-3337)
Update test client to remove reference to non-PCKE parameter support
Start webserver locally and see buttons are removed (see screenshot)
Start webserver locally and see buttons are removed (see screenshot)
etc)

BB2-3337: Update test client to remove reference to non-PCKE parameter support

---

apps/wellknown/views/openid.py
hhs_oauth_server/tests.py

[BB2-3853](https://jira.cms.gov/browse/BB2-3853)
Changes the smart config endpoints to match requirements listed in https://jira.cms.gov/browse/BB2-3853
Proper response being returned by /{v1:v2}/fhir/.well-known/smart-configuration
Ran a local instance and tested in postman
etc)

changing capabilities and scope for smart config

---

apps/health/checks.py

[BB2-3899](https://jira.cms.gov/browse/BB2-3899)
Fix Improper Certificate Validation
Tests should pass
etc)

BB2-3899: Fix Improper Certificate Validation

---

apps/authorization/v3/urls.py
apps/dot_ext/v3/urls.py
apps/fhir/server/authentication.py
apps/mymedicare_cb/views.py
hhs_oauth_server/urls.py

[BB2-3886](https://jira.cms.gov/browse/BB2-3886)
Adds v3 authorization and token endpoints
This relies on the same waffle flag from the predicate work [here](https://github.com/CMSgov/bluebutton-web-server/pull/1333). Follow the setup instructions or run the django command to create test flags locally after pulling that branch. 
In postman, set authorization and token endpoints to http://localhost:8000/v3/o/authorize/ and http://localhost:8000/v3/o/token/ respectively and request a new token. You should receive a token successfully that notes the v3 access token url as in:
* Any other changes that could …

BB2-3886: Added v3 auth endpoints

---

apps/dot_ext/utils.py
apps/mymedicare_cb/tests/test_callback_slsx.py
apps/mymedicare_cb/views.py
templates/app_inactive_401.html
templates/bene_404.html

[BB2-3915](https://jira.cms.gov/browse/BB2-3915)
Allows us to lookup client id before hitting BFD to look for user.
Attempt to perform authentication with Postman using the wrong client id. To test the request ID reporting, use the test client and log in with the non-existent user, xxlindner_user.
etc)

BB2-3924: Client ID validation before user lookup

---

apps/mymedicare_cb/views.py
templates/bene_404.html

Quick fix to remove debug statement and make redirect uri more flexible for BB2-3913.

BB2-3913: Hotfix

---

Jenkinsfiles/Jenkinsfile.cbc-run-multi-pr-checks-w-selenium-chromium

Hotfix to skip integration tests

Jenkins skip integration tests

---

Jenkinsfiles/Jenkinsfile.cbc-run-multi-pr-checks-w-selenium
Jenkinsfiles/Jenkinsfile.cbc-run-multi-pr-checks-w-selenium-chromium
apps/fhir/bluebutton/tests/fhir_resources/fhir_meta_v1.json
docker-compose.selenium.yml
docker-compose/run_integration_tests_local.sh
docker-compose/web-env-vars.env
static/openapi.yaml

[BB2-XXXX](https://jira.cms.gov/browse/BB2-XXXX)
Updates bfd endpoints from https://prod-sbx.bfd.cms.gov/ for https://prod-sbx.fhir.bfd.cmscloud.local/
Any breaking functionality or other tests necessary. Ran unit tests and selenium tests with mslsx. Any other tests that could be done or anything else to verify functionality would be appreciated.
Verified local auth and unit tests/selenium tests with mslsx
etc)

Update bfd endpoints

---

Jenkinsfiles/Jenkinsfile.cbc-run-multi-pr-checks-w-selenium-chromium

Re-adds the integration test step in Jenkins

hotfix: Returned jenkins integration test step

---

apps/fhir/bluebutton/views/generic.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py

[BB2-3891](https://jira.cms.gov/browse/BB2-3891)
[BB2-3936](https://jira.cms.gov/browse/BB2-3936)
Added BB2 v3 patient endpoint use BFD v3 patient, Coverage and EOB endpoint endpoint.
At present we are not able to test Coverage as its not in BFD yet, but these changes should work for Coverage too
1. Checkout this branch
2. Update value for property in `.env`
```
FHIR_URL="https://internal-bfd-4033-test-server-ng-alb-49032041.us-east-1.elb.amazonaws.com" 
```
3. Make changes mentioned in here https://github.com/CMSgov/bluebutton-web-server/pull/1351/files in your code. In here we have commented waffle switch just for easier testing, one can also set this flag without commenting it.
4. Create …

[BB2-3891, BB2-3936]: Added BB2 v3 patient endpoint use BFD v3 patient, Coverage and EOB endpoint endpoint

---

apps/fhir/bluebutton/tests/test_fhir_resources_read_search_w_validation.py
apps/fhir/bluebutton/tests/test_read_and_search.py
apps/fhir/bluebutton/views/generic.py
apps/fhir/bluebutton/views/search.py
apps/fhir/server/authentication.py
apps/mymedicare_cb/views.py

[BB2-3986](https://jira.cms.gov/browse/BB2-3986)
This PR adds some adjustments to allow for V3 endpoints to work correctly.
- Does not include query parameters in the request body for BFD GET requests (this was leading to a 400 error since the content-length header is not permitted in V3)
- Do not require a default of `startIndex=0` (since startIndex is prohibited for Patient/Coverage in V3)
- Set BFD endpoint to v3 when v3 BB2 endpoints are used
- (unrelated) delete duplicate logic for the bene not found case
Does auth + FHIR GET requests work on v2? How bout v3? (Note that for v3, the bfd test environment url and certs must be used.)
Is there anything else I missed? Any other cleanup?
Go through …

BB2-3986: Fix v3 authorize to be usable with v3 endpoints.

---

static/connectathon_openapi.yaml

[BB2-3986](https://jira.cms.gov/browse/BB2-3986)
Updates v3 connectathon swagger docs.
etc)

BB2-3986: Update v3 swagger for connectathon

---

apps/fhir/bluebutton/utils.py
apps/fhir/bluebutton/views/home.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py
apps/fhir/server/authentication.py
apps/fhir/server/settings.py
apps/mymedicare_cb/views.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/urls.py

[BB2-3986](https://jira.cms.gov/browse/BB2-3986)
This PR adds support for using two different BFD endpoints, one for V1/V2 and one for V3. It also adds some changes to allow for the metadata endpoint to work correctly, and for the auth flow to maintain V3 throughout.
Anything important missing? Any comments or TODOs to add?
Add the following to `.env`:
```
FHIR_URL="https://test.fhir.bfd.cmscloud.local"
FHIR_URL_V3=https://internal-bfd-4033-test-server-ng-alb-49032041.us-east-1.elb.amazonaws.com
```
and use the test env certs. Then test an auth flow with V2, followed by fhir resource requests in V2, and then do the same in V3. Both V2 and V3 should independently work.
Please indicate if this PR does …

Add support for separate V2/V3 BFD endpoints

---

.github/workflows/contributors.yml
.github/workflows/update-code-json.yml
CODE_OF_CONDUCT.md
COMMUNITY.md
CONTRIBUTING.md
README.md
SECURITY.md
checklist.md
code.json

N/A
This PR is for the [Tier 3 Outbounding](https://github.com/DSACMS/repo-scaffolder/tree/main/tier3) of this repository. This is a first pass and some additional work that I will outline below must be made before approving and merging. Once everything is confirmed accurate, we can remove the checklist and merge!
- This repository is close to meeting Tier 3 requirments. The documentation is accurate except for a few places where it needs to be filled out.
- Roles & Responsibilities in COMMUNITY.md
- Members in COMMUNITY.md
- The project must be checked to see if any PII or PHI is publicly available. A guide to answer this can be found in this checklist in the **State the Risks of Open Sourcing the …

DSAC OSPO: Tier 3 Outbounding

---

.github/workflows/contributors.yml
.github/workflows/update-code-json.yml
CODE_OF_CONDUCT.md
COMMUNITY.md
CONTRIBUTING.md
README.md
SECURITY.md
checklist.md
code.json

N/A
This PR is for the [Tier 3 Outbounding](https://github.com/DSACMS/repo-scaffolder/tree/main/tier3) of this repository. This is a first pass and some additional work that I will outline below must be made before approving and merging. Once everything is confirmed accurate, we can remove the checklist and merge!
- This repository is close to meeting Tier 3 requirments. The documentation is accurate except for a few places where it needs to be filled out.
- Roles & Responsibilities in COMMUNITY.md
- Members in COMMUNITY.md
- The project must be checked to see if any PII or PHI is publicly available. A guide to answer this can be found in this checklist in the **State the Risks of Open Sourcing the …

Merging #1360 to master

---

Jenkinsfiles/cbc-pod-deployment-config-w-selenium-p311-chromium.yaml
Jenkinsfiles/cbc-pod-deployment-config-w-selenium-p311.yaml
Jenkinsfiles/cbc-pod-deployment-config-w-selenium-p38.yaml
Jenkinsfiles/cbc-pod-deployment-config-w-selenium.yaml

[BB2-4010](https://jira.cms.gov/browse/BB2-4010)
ECR url update to pull docker images from Green field accounts.
etc)

ECR urls update for selenium PR checks

---

templates/bene_404.html

[BB2-4072](https://jira.cms.gov/browse/BB2-4072)
Updates enrollee error message
Spelling
When an enrollee doesn't exist in SLS, the new error message should display
I verified this by inserting the following code 
```
user_not_found_error = NotFound()
user_not_found_error.status_code = status.HTTP_404_NOT_FOUND
user_not_found_error.default_detail = 'Not found.'
user_not_found_error.default_code = 'not_found'
```
into mymedicare views to force a user_not_found path which serves the bene_404.html
None
* Any other changes that could …

BB2-4072: Implement new error messaging for enrollees

---

static/openapi.yaml

[BB2-4075](https://jira.cms.gov/browse/BB2-4075)
Updated examples for 3 endpoints 
1. Pull this branch
2. Copy contents of openapi.yaml
3. paste in https://editor.swagger.io/ 
4. Verify if v3 endpoints are showing up
etc)

BB2-4075: Updated examples for swagger v3 apis

---

apps/fhir/bluebutton/management/commands/user_mbi_backfill.py
apps/fhir/bluebutton/utils.py

[BB2-4145](https://jira.cms.gov/browse/BB2-4145)
This code will loop through bluebutton_crosswalk records that have a null user_mbi value. It will then ping the Patient endpoint in BFD using the fhir_id from bluebutton_crosswalk. If the user_mbi is included in the response, the bluebutton_crosswalk record will be updated.
There are the following flags for the script:
- batch-size: Number of bluebutton_crosswalk records that will be pulled back if they meet criteria. Default is 1000.
- execute: Whether or not to actually update the database when running. By default this is false, if the --execute flag is passed when running the script, then the DB will be updated
- start-user-id: The user_id value to begin at for bluebutton_crosswalk records. This will allow us to skip …

BB2-4145: User mbi backfill

---

apps/fhir/bluebutton/management/commands/user_mbi_backfill.py

No ticket
Converts log statements to prints so they will be visible when the user_mbi_backfill script is run in EC2 or Jenkims
Confirm all log statements have been remove.d
etc)

Convert log statements to prints so they will show in EC2/Jenkins logs

---

apps/health/checks.py
apps/health/tests/test_healthchecks.py
apps/health/urls.py
apps/health/views.py
apps/integration_tests/integration_test_fhir_resources.py
hhs_oauth_server/urls.py

[BB2-1110](https://jira.cms.gov/browse/BB2-1110)
Ensures that only /health and /health/ will return the all's well page. Any trailing characters after /health/ will result in a 404 page being thrown.
**Question**: Do we need the v2 endpoints? They check the same thing as the endpoint that does not have the trailing '_v2'
* Pull the branch down, start web server
* Navigate to localhost:8000/health and localhost:8000/health/. Ensure you see the all's well message. Note that localhost:8000/health will redirect to localhost:8000/health/ due to the change in the hhs_oauth_server/urls.py file.
* Navigate to the following URLs, ensure that all return 200s:
* **localhost:8000/health/** (confirms we can …

BB2-1110: Restrict health check url
