apps/accounts/views/core.py
apps/extapi/templates/extapi/intro_step1.html
apps/home/templates/index.html
hhs_oauth_server/examples/wsgi_test.py
hhs_oauth_server/hhs_oauth_server_context.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/urls.py

Create context processor for active_apps (returns list of INSTALLED_APPS)
Added Site/Installation Specific section that adds to INSTALLED_APPS:
INSTALLATION_SPECIFIC_APPS = [
'apps.extapi',
]
INSTALLED_APPS += INSTALLATION_SPECIFIC_APPS
- Removed TEMPLATE_MODE and SETTINGS_MODE from settings.base
- Documented changes in settings.base
- Modified Templates to use context processor:
#
Modified code to use IsAppInstalled from hhs_oauth_server.hhs_oauth_server_context.py
eg. 
if IsAppInstalled('apps.extapi'):
issued_invite = issue_invite(invited_email, user_type="DEV")

Add Context processor for active_apps

---

hhs_oauth_server/wsgi.py

(it was looking one folder to far up the tree.)
(this makes running apache with environment variables more robust)

Modified wsgi.py to look in parent folder above manage.py

---

apps/accounts/models.py
apps/fhir/bluebutton/tests/test_utils.py
apps/fhir/bluebutton/utils.py
apps/fhir/build_fhir/utils/utils_fhir_dt.py
apps/fhir/fhir_consent/__init__.py
apps/fhir/fhir_consent/apps.py
apps/fhir/fhir_consent/models.py
apps/fhir/fhir_consent/signals.py
apps/fhir/fhir_consent/tests.py
apps/fhir/fhir_consent/utils.py
apps/fhir/fhir_consent/views.py

Added __init__.py and apps.py to activate post_save signal to
create fhir_Consent record.
Tests create for ConsentDirective
Switched to Dstu2 ConsentDirective resource format
fixed timezone v datetime in PasswordReset to solve test error
Must use timezone.now() to deal with USE_TZ setting.
flake8 passes locally
tests pass locally

Added create consent on AccessToken post_save

---

hhs_oauth_server/settings/aws-dev.py
templates/admin/base.html
templates/admin/change_form.html
templates/admin/change_list.html
templates/admin/change_list_results.html
templates/admin/login.html
templates/admin/related_widget_wrapper.html
templates/admin/search_form.html
templates/registration/password_change_form.html
templatetags/__init__.py
templatetags/admin_static.py

[fix_admin_s3 7fc212d]
Fix admin static file storage in s3 When static fies are stored in S3 the admin_static tag corrupts the STATIC_URL setting. 
I had a similar problem with STATIC and MEDIA files in S3.
For Static and Media the solution was to override _clean_name and _normalize_name in hhs_oauth_server/s3_storage.py 
For Admin and Registration the solution is to: 
- create an admin folder in templates 
- copy any django/contrib/admin/templates/admin files that used {% admin_static %} to templates/admin 
- copy any django/contrib/admin/templates/registration files using {% admin_static %} to: templates/registration. 
then: 
replace admin_static with static in {% load %} statement

Fix admin_static in s3

---

hhs_oauth_server/settings/base.py
templates/admin/base.html

with {% load admin_static %} in template and S3 storage used.
{% static '{static filename}' %} gets presented as:
https://s3.amazonaws.com/{AWS_STORGAGE_BUCKET_NAME}/{static filename}/static
switching to {% load static %} and {% static '{path}' %} get presented as:
https://s3.amazonaws.com/{AWS_STORGAGE_BUCKET_NAME}/static/{static filename}

More patches to solve admin_static incorrectly formated.

---

hhs_oauth_server/settings/base.py
templates/admin/auth/user/change_password.html
templates/admin/base.html
templates/include/footer.html

Added settings.ALLOWED_HOSTS|Last in footer.htl to display server that code is running on. This is to help debugging and quick patching.
Done as part of solving admin static file issue with S3. Admin static files are being /static terminated and not displaying correctly.
This is an S3 problem because files are presented correctly locally.

Temporarily add ALLOWED_HOSTS to settings decorator in base.py

---

hhs_oauth_server/settings/aws-dev.py
hhs_oauth_server/settings/aws-impl.py
hhs_oauth_server/settings/aws-prod.py
hhs_oauth_server/settings/aws-test.py
hhs_oauth_server/settings/base.py

Debug mode is currently enabled in our sandbox environment at sandbox.bluebutton.cms.gov.
In general, debug mode should not be enabled in any public-facing environment. If our dev and test environments were only accessible via OpenVPN, we could enable this mode. As it is, this isn't an option. I removed the option to even set it otherwise outside of a local environment.

Turn off debug mode in sandbox

---

apps/fhir/bluebutton/utils.py

Logging is only showing ELB Addresses. We need to see if we can capture
the originating ip address received at the ELB.

adding query for originating ip address to perf_mon output.

---

apps/dot_ext/forms.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/settings/dev.py
hhs_oauth_server/settings/test.py

switch REQUIRE_HTTPS_REDIRECT_URIS to BLOCK_HTTP_REDIRECT_URIs
This enables mobile apps to use web hooks registered on the mobile device but prevents the use of http:// endpoints in production.
The web deployment scripts have been updated in sync with these changes.
https://issues.hhsdevcloud.us/browse/CBBP-845

enable mobile redirect uris (CBBP-845)

---

apps/dot_ext/throttling.py
apps/fhir/bluebutton/decorators.py
apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py
hhs_oauth_server/settings/base.py
hhs_oauth_server/settings/test.py
requirements/requirements.in
requirements/requirements.txt

- On a per-token basis throttle access to `read` and `search` views.
- Uses the [throttling interface from django rest framework](http://www.django-rest-framework.org/api-guide/throttling/)
- When enabled responses will include the same rate limit [headers as github](https://developer.github.com/v3/rate_limit/)
- In production this requires a [cache](https://docs.djangoproject.com/en/2.0/topics/cache/) to be configured for Django, it will work with the in memory cache as a default but that will not sync accross an auto scaling group.

CBBP-817 - Token based throttling on protected views

---

apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py

The DRF Request object type does not behave in
the same way as Django's HttpRequest and broke
downstream code.
The `request` variable was pointed at
the django `request._request` HttpRequest
in DRF wrapped views.

Set request to django.HttpRequest in authed views

---

apps/dot_ext/throttling.py

The math was flipped for calculating the remaining number of calls.
There is another set of ratelimiting logic `django-ratelimit` being used for the `accounts` app. Should we consider consolodating to one tool?

Correcting x-RateLimit-Remaining math

---

hhs_oauth_server/settings/base.py

This setting turns out to be extremely problematic when taking POST requests. It literally results in an endpoint guaranteed to return a 500 error. I'm not certain this is responsible for any of the issues our developers are experiencing, but it very well may be. This is of no value to an API, and of potential danger.

Set APPEND_SLASH to false

---

templates/404.html
templates/500.html

See, for example, sandbox.bluebutton.cms.gov/im-not-a-url:
Old
New

Set 404 header to non-italic style

---

apps/dot_ext/oauth2_validators.py

The math being used to calculate expires_in when
returning existing tokens was returing a float.
This causes oauth libraries like go's to encounter
an error when trying to parse the returned token.
The calculated expires_in is now floored before being set.

When returning existing tokens use whole seconds

---

apps/mymedicare_cb/views.py
hhs_oauth_server/settings/dev.py

By default the user will now be forwarded to account.mymedicare.gov,
locally developers can still choose local login if they wish.

CBBP-882 Allow auto redirect to account.mymedicare.gov

---

apps/dot_ext/forms.py
apps/dot_ext/scopes.py
apps/dot_ext/templates/oauth2_provider/application_detail.html
apps/dot_ext/tests/test_scopes.py
apps/dot_ext/tests/test_views.py

In order to acheave this all applications appear to have all scopes.
The alternative is to rip out the scope behavior completely, which seems to be engrained in the oauth2_provider library. Thoughts?

CBBP-881 Do not restrict applications by scope

---

apps/dot_ext/oauth2_validators.py

Allows client libraries that present the `redirect_uri` as optional to be used with less friction.

CBBP-916 Use default redirect_uri if none is passed

---

hhs_oauth_server/urls.py

Allows us to change a setting for prod to return a 404 error when the user visits api.sandbox.bluebutton.cms.gov
We will likely move many more URLs under this flag later, but I wanted to keep it simple given the timing.

Remove prod homepage

---

apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py
apps/fhir/parsers.py
apps/fhir/renderers.py
apps/testclient/tests.py

Treat this media type the same as application/json.
Gives us a place to do any custom rendering/parsing that might be needed in future.

CBBP-950 Accept and handle the application/fhir+json type

---

hhs_oauth_server/wsgi.py
requirements/requirements.in
requirements/requirements.txt

Looks for a `newrelic.ini` file alongside (in the same location as `custom-envvars.py`), loading the config if it is found. Meant to accompany https://github.com/CMSgov/bluebutton-web-deployment/pull/1254.

CBBP-957 If New Relic ini file is present, configure the NR agent

---

hhs_oauth_server/settings/base.py
templates/design_system/base.html
templates/include/foot.html

Note to @rnagle and @ekivemark ..
This introduces a new setting:
TEALIUM_ENV = env('DJANGO_TEALIUM_ENV', 'prod')
I assume the 2 values will just be `prod` and `sandbox`.  Here is the code added the django snipit.
<script>window.tealiumEnvironment = "{{ settings.TEALIUM_ENV }}";</script>
<script src="//tags.tiqcdn.com/utag/cmsgov/cms-bluebutton/{{ settings.TEALIUM_ENV }}/utag.sync.js"></script>
Gets rendered as:
<script>window.tealiumEnvironment = "prod";</script>
<script src="//tags.tiqcdn.com/utag/cmsgov/cms-bluebutton/prod/utag.sync.js"></script>

Googanl + Login copy text update

---

hhs_oauth_server/settings/base.py

Allows cache access and management accross
instances and python processes

CBBP-889 Default django's cache to the database

---

apps/accounts/end_user_signup_forms.py
apps/accounts/models.py
apps/fhir/bluebutton/models.py
hhs_oauth_server/settings/base.py

Builds on and is meant to take the place of work in https://github.com/CMSgov/bluebutton-web-server/pull/566.
Instead of providing a `bool` setting for switching between string and hex string depending on env, always treat the `USER_ID_SALT` as a hex-encoded value.

CBBP-1017 Add get_user_id_salt to handle decoding hex str value for user id salt

---

templates/404.html

The reverse call to home in the template caued a cascade of errors when NO_UI was enabled.
NO_UI removes "home" from the route table

Remove link to home in 404 template

---

apps/dot_ext/admin.py
apps/fhir/bluebutton/admin.py

The lack of the client_id column was making it very difficult to find the apps our developers wanted added to production. This makes it easier!

Add client ID to admin

---

apps/fhir/bluebutton/tests/test_read.py

The order of query parameters can change causing tests to fail intermittently

Test for explicit URL structure

---

ops/build_release.sh

Adding a step to `build_release.sh` to generate release notes based on the commits since the last release.
As an example, if we compare what's currently on `release-notes` branch to the previous release (`r11`), it produces notes that look like:
```
release-notes - 2018-05-01
================
- add release notes generation/update step to build_release.sh
- Test for explicit URL structure (#592)
- Raise exception for failure response from backend (#591)
- Merge pull request #590 from CMSgov/develop
```
Since we've change our merge strategy to "squash and merge," if we tag `r12` after merging this PR, the notes should look like:
```
r12 - 2018-05-01
================
- [CBBP-986] Generate release notes based on commit message
- Test for explicit URL structure (#592)
- Raise exception for …
```

[CBBP-986] Generate release notes based on commit message

---

apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/views/generic.py
apps/test.py

Allows tokens created for Beneficiaries that did not have a match in the system to be used and updated once a match does exist in the system.

Recheck fhir_id on any request if it is empty

---

hhs_oauth_server/urls.py

http errors don't make sense for API responses.
This simplifies our behavior.

Return application/json on 4xx/5xx errors

---

ops/build_release.sh

Couple minor tweaks:
- Don't rely on `RELEASE.txt` to be present
- Try to determine if the script is being run from top-level directory earlier in the process
- Direct error output to stderr

Tweaks to ops/build_release.sh

---

apps/home/templates/index.html

Bad link shows up on api.bluebutton.cms.gov home page when not logged in.
missing ">"
Also re-direct to sandbox for signup.

BLUEBUTTON-371: Bad link shows up on api.bluebutton.cms.gov home page

---

apps/dot_ext/forms.py
apps/dot_ext/tests/test_forms.py

* Change queryset for application name duplicate check to be case insensitive.
* Django tests for the 'name' field validation in the CustomRegisterApplicationForm form.

Bluebutton 427 unique app names case insensitive

---

apps/accounts/templates/email-activate.html
apps/accounts/templates/email-activate.txt

Just a few template changes to fix the links for the activation email (email sent after signup w/ activation key).

BLUEBUTTON-491 Fix links in activation email templates

---

apps/dot_ext/forms.py
apps/dot_ext/migrations/0005_auto_20180122_1553.py
apps/dot_ext/models.py
apps/fhir/bluebutton/authentication.py
apps/fhir/bluebutton/tests/test_read.py
apps/metrics/views.py
hhs_oauth_server/request_logging.py

This PR adds items and functionality needed for Jira tickets 363 and 364. This is info for putting developers in to Group2 or Group3 categories.
Summary of major changes:
* Added first_active and last_active datetime fields to the Application model.
* first_active and last_active datetimes are updated under OAuth2ResourceOwner() authentication class.
* Added filters related to activity and app_count (application count per developer).
* Moved the ToS agreement logging on the application model save() to the form save() override.
* Changed Application model op_tos_uri field to default to settings.TOS_URI.
* Added tests to check that application activity fields update for a resource call.

BLUEBUTTON-363 BLUEBUTTON-364 Get info on devs for Group2/3

---

apps/fhir/bluebutton/admin.py

This fixes the admin crosswalk list when a fhir_source attribute is NoneType.

Fix Crosswalk admin list to handle Null fhir_source

---

templates/design_system/base.html
templates/include/foot.html

Previously crazy egg was placed within the design-system base.html - In this PR I'm placing it in foot.html (at the end) which is loaded by template/base.html - Pulling this in at the bottom should keep page loads snappy and it's where other scripts are referenced as well.

609: Adding 'Crazy Egg' script

---

apps/accounts/templates/account-settings.html
templates/generic/bootstrapform.html
templates/include/messages.html

This fixes some of the last bugs that Cat found with the Bootstrap removal.
- Makes the Signup page properly responsive.
- Switches the "top-of-page" errors/messages to follow CMS Design system instead of Bootstrap.
Here is an example of the updated message:

BLUEBUTTON-633 Remaining Bootstrap Removal Fixes

---

apps/wellknown/urls.py

Summary:
This adds a feature switch called "wellknown_applications" to control enabling and disabling of the /.well-known/applications endpoint. If this switch is missing, the default is to disable the endpoint.
NOTE: This was previously controlled via the deployment repository and NGINX configuration using IP address range restrictions.

BLUEBUTTON-862 Make applications list public on next release to PROD

---

apps/core/management/commands/create_test_feature_switches.py
docker-compose/migrate.sh

Since we've added the use of Waffle feature switches to the project, they all default to False when running locally via the docker-compose setup. So features like login and signup are disabled until the related switch is created.
This PR creates a management command that is called via the docker-compose/migrate.sh script. This command creates the switches during setup so that this doesn't need to be done manually via ADMIN.

Create waffle switches for local development testing

---

apps/logging/serializers.py

SUMMARY:
This is to resolve logging errors when objects are NoneType.

BLUEBUTTON-839 Resolve log errors when objects are NoneType

---

apps/wellknown/urls.py
apps/wellknown/views/__init__.py
apps/wellknown/views/application.py

Summary:
This lists out application category labels at the following endpoint:  /.wellknown/application-labels
Label slugs in the settings.DJANGO_APP_LIST_EXCLUDE list are excluded from the listing.
The endpoint is attached to the feature switch = "wellknown_applications" .

BLUEBUTTON-903 Create app category labels endpoint

---

apps/wellknown/views/application.py

Summary:
This creates a "label" filter on the /.well-known/applications list endpoint. The "label" filter parameter can include a listing of ApplicationLabel "slug" names. If an application belongs to a label category with the slug name, it will be listed.
URL EXAMPLE:   <base URL>/.well-known/applications?label=slug-one,slug-two,slug-three

BLUEBUTTON-900 Create labels filter on application list endpoint

---

apps/dot_ext/admin.py
apps/dot_ext/forms.py
apps/dot_ext/models.py
apps/dot_ext/tests/test_forms.py

This removes the text size and HTML tag validations on the application description when editing via the Django ADMIN.

BLUEBUTTON-919 Remove app description validations from ADMIN

---

apps/accounts/forms.py
apps/accounts/tests/test_case_ins_username.py
apps/accounts/views/core.py
apps/dot_ext/forms.py

NOTE: I also changed the logo_uri field in the application registration form to use the field disabled=True option versus using the widget's "readonly" attribute. This is a better method and prevents the ability to update the field via client side tampering.

BLUEBUTTON-937 Disable email field in AccountSettingsForm

---

apps/fhir/bluebutton/admin.py
apps/fhir/bluebutton/models.py
apps/metrics/urls.py
apps/metrics/views.py
templates/admin/bluebutton/crosswalk/change_list_object_tools.html

Summary:
* This adds an action to the crosswalks ADMIN for migrating positive fhir_id's to negative values. 
* Only crosswalks that have a resource router fhir_url that hashes to match the ALLOWED_FHIR_URL_HASH can be updated.
* The functionality is also protected by needed the "admin_crosswalk_dpr_sync" feature switch for the action to show in the ADMIN.
* The crosswalk's user_id_hash does not get updated during the migration.

BLUEBUTTON-938 dpr switch in test

---

apps/fhir/bluebutton/views/generic.py
apps/fhir/bluebutton/views/search.py

Allow `type` query param
Allowed values are specified by:
- https://bluebutton.cms.gov/resources/codesystem/eob-type
- https://confluence.cms.gov/pages/viewpage.action?spaceKey=BB&title=Allowing+3rd+parties+to+filter+EoB+Searches+by+Type
Respond to incorrect query params with a 400 
Described behavior that appears to implement:
- `type` is an allowed query parameter.
- limit `type` values to allowed set.
- return an error if the values are outside of that set.
A sanity check for values in addition to usual review standards.
- [BLUEBUTTON-1065](https://jira.cms.gov/browse/BLUEBUTTON-1065)
New query params and values will be passed back to the FHIR server. See description for specification.
See above

Claim type filter

---

apps/dot_ext/forms.py
apps/dot_ext/templates/oauth2_provider/application_form.html

For acceptance, I think it should be evident that the defined error messages will show up in the form.
Mostly this: Am I implementing this properly? I removed what appeared to be a duplicated error message from `forms.py` - just want to make sure that's accurate. 
I also think if I had more time to work on this ticket, I would a few extra things. I am curious if we think this is a good idea for a future ticket:
- Update the error messages themselves to be more readable
- Combine the two types of error messages (generated by the two `for` loops) into one alert container, with each error message being an `<li>`.
- Make sections of the errors themselves links to the corresponding field. That way, a user (especially a user with a screen reader/keyboard navigation) could easily jump from the …

BLUEBUTTON-1334 Error Message Styling

---

static/js/sandbox-main.js

While smoke testing the sandbox on dev, I encountered an IE bug that I had missed. Apparently IE 11 doesn't support `forEach`, which I used for the credentials toggle functionality as well as the accordion functionality.
I tested to make sure the functionality still works and it looks good, so I am really just looking for confirmation of the plan / consistent implementation.
No Jira ticket for this, just a bug I found while smoke testing.
No security implications with this fix.

Removes forEach for IE compatibility and speed

---

apps/dot_ext/tests/test_authentication.py
apps/dot_ext/tests/test_views.py
apps/fhir/authentication.py

Stop truncating SLS GUID when creating a user record. This creates the risk for user collisions.
UserName in User Model and in linked tables reflects the full GUID returned from SLS.
@dtisza1: Is any additional logging required?
- [BLUEBUTTON-1665](https://jira.cms.gov/browse/BLUEBUTTON-1665)
If User name collisions occur there is a risk of different FHIR records being returned to a user.
Ensuring a Unique GUID from SLS will eliminate that risk.
N/A
N/A
GUID is no longer truncated. Previously the guid was shortened to id[9:36]
We do not for see any impact to security. This eliminates the risk of PHI/PII Leakage.

BLUEBUTTON-1665 Remove SLS uuid truncation

---

apps/fhir/bluebutton/admin.py

This fixes a bug in the Crosswalk Django Admin where a search produces a 500-error.
One of the search fields was change from `fhir_id` to the use the internal `_fhir_id` to resolve.
That a search in the Crosswalk Admin produces the expected results and does not error.
- [BLUEBUTTON-1728](https://jira.cms.gov/browse/BLUEBUTTON-1728)

BLUEBUTTON-1728 Crosswalk ADMIN search 500-error

---

apps/fhir/bluebutton/tests/test_read.py
apps/fhir/bluebutton/views/generic.py
apps/fhir/bluebutton/views/search.py

This adds `_lastUpdated` to the allowed list of parameters for FHIR resource requests.
There is more information about this parameter here:  https://github.com/CMSgov/beneficiary-fhir-data/blob/d3da960f238f26e66702fd7f13cc87d67583a3da/rfcs/0004-since-parameter.md
That the `_lastUpdaed` parameter is validated and included in the request to the BFD. It will also handle multiple parameters to produced a data/time search range.
- [BLUEBUTTON-1860](https://jira.cms.gov/browse/BLUEBUTTON-1860)

BLUEBUTTON-1860 Allow list the _lastUpdated parameter for FHIR resource requests

---

apps/fhir/bluebutton/views/search.py

The `query_schema` in the `SearchView()` class was updated to handle a comma separated list of values for the claim-type parameter. This is used for filtering the resource parameters using the Voluptuous data validation library.
That the claim type parameter can handle multiple comma separated values.  For example, `type=snf,https://bluebutton.cms.gov/resources/codesystem/eob-type|pde,hospice`
- [BLUEBUTTON-1563](https://jira.cms.gov/browse/BLUEBUTTON-1563)

BLUEBUTTON-1563 Claim type parameter in Front-end doesn't handle multiple types

---

hhs_oauth_server/settings/base.py

The configuration for prepending a string to the admin url was unintentionally removed by a typo, this adds it back in.
The typo is corrected.
https://github.com/whytheplatypus/bluebutton-web-server/blob/55e6f2106f4d84dd457de8cff1e4a24685924015/hhs_oauth_server/settings/base.py#L441

Correct admin url prepend conf

---

dev-local/msls/login_form.go
dev-local/msls/main.go

[BB2-126](https://jira.cms.gov/browse/BB2-126)
As a developer working with BB2 in a local development environment (for details refer to: https://github.com/CMSgov/bluebutton-web-server/tree/master/docker-compose), I need the local MSLS service ( a simulator of SLS identity provider service) accept MBIas beneficiary identity in addition to HICN. 
Currently, the local MSLS service (implemented in golang) is up and running at localhost:8080 as a dependency service when BB2 service starts, it participates in OAUTH2 flow by collecting beneficiary identity and providing user info (user name (sub), one form of identity: hicn, and optionally: first name, last name, email) to the authentication and authorization flow.
With inclusion of MBI as a form …

BB2-126: Update MSLS container to include MBI for local development - msls service

---

apps/dot_ext/forms.py
apps/dot_ext/tests/test_form_application.py
apps/fhir/bluebutton/tests/test_models.py
apps/test.py

[BB2-66](https://jira.cms.gov/browse/BB2-66)
As BB2 Production Application On boarding Administrator, the current process of adding new applications is login
in as BB2 Admin, and using BB2 Admin Console to add application(s) for a particular user, for detailed steps, refer to 
[BB2-66](https://jira.cms.gov/browse/BB2-66) comments.
Bug / Issue:
If a new application is created through BB2 Admin console, and a logo is uploaded during the process, logo_uri is calculated
from the hash of application object's PK (primary key), due to the bug, when logo_uri is calculated, the application's PK is always None because it is not saved yet, this is causing logo_uri collision for all the applications added in a session.
However, if an application is …

BB2-66 Fix-logo-display-in-Published-Applications-API

---

apps/dot_ext/tests/test_app_form_templates.py
templates/include/app-form-optional-info.html

[BB2-220](https://jira.cms.gov/browse/BB2-220)
As BB2 Developer Sandbox user (external app developer), I want to create (register) my applications with "Customer Support Phone Number" among other info such as terms and privacy policy etc., BB2 application edit page provide a field where a support phone number can be provided - typed in, however, after click "Save" the application registration form, and come back to application edit page, the "Customer Support Phone Number" field is blank.
Findings:
Debugging shows that BB2 model object Application has attribute "support_phone_number", however, the application edit page
template expects attribute "support_phone" as shown below:
BB2-SRC-BASE-DIR/templates/include/app-form-optional-info.html: …

jfuqian/BB2-220 Sandbox-App-Edit-Page-Not-Show-PhoneNumber

---

apps/fhir/bluebutton/tests/data_conformance.py
apps/logging/signals.py
hhs_oauth_server/settings/base.py

[BB2-218](https://jira.cms.gov/browse/BB2-218)
As a BB2 developer and administrator and analytical tools which consume audit events from BB2 logs, I expect an audit event: type:AccessToken, action:revoked logged whenever an access token is deleted through BB2 ADMIN UI.
ADMIN UI is used as BB2 token and grant manager, in BB2 ADMIN, there are THREE places you can revoke an access token:
(1) "Access Token" link under section "DJANGO OAUTH TOOLKIT", to go to "Access Token" manage page, to add, delete access token
(2) "My Access Token" link under section "BLUEBUTTON", to go to "My Access Token" manage page, to add, delete my access token
(3) "Data Access Grant" link under section "PROFILE", to go to "Data Access Grant" manage page, to add, delete …

BB2-218 BB2-Fail-to-log-AccessToken-Revoke-AuditEvent

---

apps/fhir/bluebutton/models.py
apps/fhir/bluebutton/tests/test_models.py
apps/fhir/bluebutton/tests/test_utils.py
apps/fhir/server/authentication.py
apps/fhir/server/loggers.py
apps/fhir/server/tests/responses.py
apps/fhir/server/tests/test_authentication.py
apps/mymedicare_cb/loggers.py
apps/mymedicare_cb/models.py
apps/mymedicare_cb/tests/test_callback.py
apps/mymedicare_cb/tests/test_models.py
apps/mymedicare_cb/validators.py
apps/mymedicare_cb/views.py
hhs_oauth_server/settings/base.py
tox.ini

[BB2-132](https://jira.cms.gov/browse/BB2-132)
As a BB Engineer, I need to utilize the MBI hash stored in the crosswalk table so that I can use this identifier to lookup beneficiaries via the patient resource endpoint of the BFD. 
This PR is a continuation of the work done for [BB2-54 Store MBI hash in crosswalk for use with patient resource lookups](https://jira.cms.gov/browse/BB2-54) [PR #806](https://github.com/CMSgov/bluebutton-web-server/pull/806)
NOTE: I've changed the discription below, since a lot of rebasing and renamings were done. Please see the details in the commits for more information on those changes.
The following are the main areas of changes related to this PR. I am writing this while doing a self review of the PR. The …

BB2-132 Use stored MBIs with patient resource lookups

---

apps/capabilities/tests.py
apps/dot_ext/forms.py
apps/dot_ext/oauth2_backends.py
apps/dot_ext/tests/test_beneficiary_demographic_scope_changes.py
apps/dot_ext/tests/test_form_oauth2.py
apps/dot_ext/tests/test_views.py
apps/dot_ext/views/authorization.py
apps/logging/serializers.py
apps/logging/signals.py
templates/design_system/authorize_v2.html

[BB2-264](https://jira.cms.gov/browse/BB2-264)
As a team, we need to disable past access tokens to ensure that new user preferences against phase 1 scopes are recognized. 
This PR adds the following:
- Past access and refresh tokens are disabled when a beneficiary has chosen not to share demographic data. 
- Logging is added against user preference updates regarding demographic data sharing. 
- Unit testing is created to test access and refresh token behaviors. 
This PR adds improvements to previous work done for [BLUEBUTTON-1647](https://jira.cms.gov/browse/BLUEBUTTON-1647). BLUEBUTTON-1647 Demographic filter scopes phase1 #788
Notes from the commit history:
* Add missing tests for switch `require-scopes=False`
- Add …

BB2-264 Update P1 scopes to disable past access tokens

---

requirements/requirements.dev.txt
requirements/requirements.in
requirements/requirements.txt

[BB2-1029](https://jira.cms.gov/browse/BB2-1029)
Weekly security audit Snyk scan reported one medium vuln:
details are shown below:
django Access Restriction Bypass
VULNERABILITY
CWE-284
CVE-2021-44420
CVSS 5.3 MEDIUM
SNYK-PYTHON-DJANGO-2312875
SCORE
551
Introduced through
django@2.2.24, django-bootstrap-form@3.4 and others
Fixed in
django@2.2.25, @3.1.14, @3.2.10
Exploit maturity
NO KNOWN EXPLOIT
Show less detail 
Detailed paths and remediation
Introduced through: project@0.0.0 › django@2.2.24
Fix: Upgrade django to version 2.2.25 or 3.1.14 or 3.2.10 
Introduced through: project@0.0.0 › django-bootstrap-form@3.4 › django@2.2.24
Fix: Pin django to version 2.2.25 or 3.1.14 or 3.2.10 
Introduced through: project@0.0.0 › …

[BB2-1029] Bump Django 2.2.24 To 2.2.25 To Mediate Vuln (Access Restriction Bypass)

---

templates/base.html

[BB2-1929](https://jira.cms.gov/browse/BB2-1929)
DESCRIPTION
On my Android, there is a text wrapping issue with the "Here's how you know" text. The text should tuck under "An official website of the US Government" like it does on Medicare.gov.
(see attached screenshots)
ACCEPTANCE CRITERIA
"Here's how you know" text appears under "An official website of the US Government"
This bug affects Android users accessing the static site or the permissions screen as part of an app authorization flow. 
QA
1. Button link label text "Here's how you know" appears under "An official website of the US Government" on Android phones (or any mobile device with narrow screen size)
2. Button link "Here's how you know" text appears" will appear on the right hand …

[BB2-1929] Fix us gov banner rendering issue on mobile device

---

apps/creds/utils.py

[BB2-2725](https://jira.cms.gov/browse/BB2-2725)
The credentialing link is providing a hashed version of the client secret instead of the unhashed version.
Changes the field naming from `client_secret` to `client_secret_plain` in the related line of code.
That the unhashed version is now showing for the credentialing link for both on the page and download methods.
- If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
- Does this PR add any new software dependencies? **No**.
- Does this PR modify or invalidate any of our security controls? **No**.
- …

BB2-2725 Credential link is providing a hashed client secret

---

apps/testclient/management/commands/create_test_users_and_applications_batch.py
docker-compose/readme.md

[BB2-2818](https://jira.cms.gov/browse/BB2-2818)
This change adds options on an existing Django command that will allow
developers to specify how many dev users, synthetic bene users, and applications
in their local environment to be able to test with. If no options are specified on the
call, then the defaults are what the old hard coded values were.
* Adds command options to create_test_users_and_applications_batch
* Updates the README with this new information, removes broken link
* Adds directory with .rif files needed for the command to generate users/apps
* Broken link was removed in README and subsequent ticket will include the information about 
BFD synthetic data. …

BB2-2818 Update batch create users and apps command

---

apps/authorization/management/commands/change_all_access_type.py

[BB2-2894](https://jira.cms.gov/browse/BB2-2894)
This change adds a Django command that will change all applications'
data access type to THIRTEEN MONTH.
Checks first if the app is already the thirteen month type and if not, changes it.
* Changes types for all applications appropriately.
* Does …

BB2-2894 Add script to change all apps to 13 month data access

---

Dockerfile.selenium
apps/authorization/management/commands/update_access_grants.py

[BB2-3243](https://jira.cms.gov/browse/BB2-3243)
We have switched all Sandbox apps over to 13-month category. However, any existing (synthetic) access grants won't have an end date to them unless we run a script to update those. This task is to create and run a script to update all EXISTING access grants so they have an end date, 13 months from the date of the script running.
Addresses the need to apply access grant updates to all applications.
* Locally run the script with various kinds of access grants
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact …

BB2-3243: Add --all option to update_access_grants Django command

---

apps/accounts/admin.py

[BB2-3232](https://jira.cms.gov/browse/BB2-3232)
I'd like to delete sandbox accounts which have had their activation keys expired. To facilitate this, I'm delivering code that will add some filters to the Users view in Django admin. We will now be able to filter by `Active` (users with Active status), `Inactive` (users with Inactive status), and `Inactive (expired activation key)` (users with inactive status and an expired activation key). By selecting the third option, it will be simple to delete all never-activated users as required by the ticket.
This PR adds a new filter to the Users admin view as described above.
If you have any knowledge of places we have unit tested this kind of code, let me know! I would love to add unit tests for …

BB2-3232: Filter inactive accounts

---

apps/dot_ext/forms.py
apps/dot_ext/tests/test_form_application.py
templates/include/app-form-required-info.html

[BB2-2660](https://jira.cms.gov/browse/BB2-2660)
As a Builder, I want to register an app quickly without seeing unnecessary fields, so that I can have a simplified developer experience
Implementation Details
Currently on the ["register a new application" form](https://sandbox.bluebutton.cms.gov/v1/o/applications/register/) there are two fields that only have one option.
OAuth - Client Type
Authorization Grant Type
There's no need to show these fields anymore since the options can't be changed, and we display the info for them on the success screen after registering an app
* TODO
* If the answer to any of the …

Remove unnecessary fields from Register an App form BB2-2660

---

apps/fhir/bluebutton/v2/urls.py
apps/fhir/bluebutton/views/read.py
apps/fhir/bluebutton/views/search.py
docker-compose/source_env_secrets_from_aws.sh
docker-compose/web-env-vars.env

[BB2-3290](https://jira.cms.gov/browse/BB2-3290)
Updates the feature branch to be able to seamlessly connect to BFD's test environment to retrieve C4DIC resources.
Run locally and test API calls to retrieve resources from test.bfd.cms.gov. (Note that you might need to use Cisco AnyConnect instead of ZScaler to do this)
* Does this PR add any new software dependencies? **Yes** or **No**.
* Does this PR modify or invalidate any of our security controls? **Yes** or **No**.
* Does this PR store or transmit data that was not …

BB2-3290: Connect to BFD test environment for C4DIC

---

apps/fhir/server/authentication.py
apps/fhir/server/tests/test_authentication.py
apps/mymedicare_cb/models.py
apps/test.py
hhs_oauth_server/settings/base.py

[BB2-3317](https://jira.cms.gov/browse/BB2-3317)
Deprecate using hashed MBI to lookup FHIR_ID in BB2 authorization flow, use MBI instead
etc)

BB-3317: Deprecate using hashed MBI to lookup FHIR_ID in BB2 authorization flow, use MBI instead

---

apps/docs/templates/openapi.html
static/openapi.yaml

[BB2-3353](https://jira.cms.gov/browse/BB2-3353)
Initialize oAuth and allow logout flow in openapi
etc)

BB2-3353 Initialize oAuth and allow logout flow in openapi

---

apps/dot_ext/views/authorization.py

[BB2-3532](https://jira.cms.gov/browse/BB2-3532)
Adds a check for whether or not the feature flag for data access grants is active. If it is not, then the ag expiration date will always be an empty string.
While testing, use your local app and uncheck the "Superusers" box on the waffle flag for "limit_data_access". This option will otherwise pretend that the flag is always on for superuser accounts, complicating testing.
Create a local app, set the local waffle flag superuser option to false, then get an access token for your app. The expiration date field should be an empty string. If you flip the flag back on for superusers or enable it for your app, you will see a date again.
Please indicate if …

BB2-3532: Added check for flag for ag_expiration info

---

apps/docs/templates/oauth2-redirect.html

[BB2-3470](https://jira.cms.gov/browse/BB2-3470)
Currently when user authorizes on swagger UI and on consent screens if they click on cancel then UI shows blank page. 
This PR redirects back to swagger UI page on cancel
1. Start web server locally
2. Go to http://localhost:8000/
3. Click on API Reference
4. On Swagger UI page, Click on Authorize, and enter relevant details and click on Authorize
5. Enter medicare.gov login credentials
6. On Authorization screen, click on cancel instead of continue
7. It should be redirected to Swagger UI page. Before this PR it was showing blank page
* Modifies any security …

BB2-3470: Redirect to swagger UI on deny authorization

---

apps/fhir/bluebutton/tests/test_utils.py
apps/fhir/bluebutton/utils.py
apps/fhir/bluebutton/views/home.py
apps/wellknown/tests.py
apps/wellknown/urls.py
apps/wellknown/views/__init__.py
apps/wellknown/views/openid.py
hhs_oauth_server/urls.py
static/openapi.yaml

[BB2-3360](https://jira.cms.gov/browse/BB2-3360)
Adds SMART on FHIR endpoint listing out configuration details
Expected endpoint returns correct info as per https://confluence.cms.gov/pages/viewpage.action?spaceKey=BFD&title=BFD-3378%3A+FHIR+IG+conformance
Any ways the code style itself could be improved upon. It was mostly copy pasted from the openid config endpoint and it would be good to know if it is conforming to the quality of code we'd like.
This was verified by spinning up the docker containers locally, getting a token, and performing a GET request in postman to localhost:8000/.well-known/smart-on-fhir-configuration. 
A response from a local test is here:
{
"issuer": "http://localhost:8000", …

adding smart on fhir configuration endpoint

---

apps/authorization/models.py
apps/authorization/tests/test_data_access_grant.py
apps/authorization/tests/test_data_access_grant_permissions.py
apps/core/management/commands/create_test_feature_switches.py
apps/dot_ext/models.py
apps/dot_ext/tests/test_authorization.py
apps/dot_ext/tests/test_models.py
apps/dot_ext/views/authorization.py
apps/logging/loggers.py
apps/logging/management/commands/log_global_state_metrics.py
apps/logging/tests/test_loggers_management_command.py

[BB2-3549](https://jira.cms.gov/browse/BB2-3549)
After rollout of the limit_data_access flag has been completed, we will remove the checks within the web-server repo for the limit_data_access flag. Most of the work will be removing the nested if check, such as:
`if self.data_access_type == "ONE_TIME":
flag = get_waffle_flag_model().get("limit_data_access")            
if flag.rollout or (flag.id is not None and flag.is_active_for_user(self.user)): `
In the above case, everything after the data access type check would be removed and the following code block would go under the previous if block.
There are also calls within test_data_access_grant.py and test_authorization.py that are
`@override_flag('limit_data_access', active=True)`
and these would need to be removed.
1. …

Jimmyfagan/bb2-3549-Remove feature flag calls from web-server

---

.pre-commit-config.yaml

[BB2-3573](https://jira.cms.gov/browse/BB2-3573)
Updates our flake8 version to match the version used in our CI checks.
Does the pre-commit still work locally?
1. On `master`, in `openid.py`, line 119, replace `del (data` with `del(data` and save the file
2. Try to commit with `git commit -a`
3. Confirm that flake8 didn't give any errors (though don't enter a commit message and allow the commit to fail since you don't want to commit that)
4. Repeat the same steps on this branch, and confirm that the commit fails due to no whitespace after `del` in the line you edited.
* Adds …

BB2-3573: Update flake8 to match our CI checks

---

apps/wellknown/views/openid.py
static/openapi.yaml

[BB2-3642](https://jira.cms.gov/browse/BB2-3642)
Updated `authorization_grant_type` from `authorization-code` to `authorization_code` for both endpoints
/.well-known/openid-configuration
/.well-known/smart-configuration
1. Start webserver locally
2. Make below postman request and verify `grant_types_supported` should contain `authorization_code` instead of `authorization-code`
GET http://0.0.0.0:8000/.well-known/openid-configuration
```
{
"issuer": "http://localhost:8000",
"authorization_endpoint": "http://localhost:8000/v2/o/authorize/",
"revocation_endpoint": "http://localhost:8000/v2/o/revoke_token/",
"token_endpoint": "http://localhost:8000/v2/o/token/",
"userinfo_endpoint": …
```

BB2-3642: Update grant_types_supported and references to authorization_code grant type

---

splunk/api_big_stats_dashboard.xml
splunk/authorization_flow_dashboard.xml

[BB2-3466](https://jira.cms.gov/browse/BB2-3466)
1. Improve Panel "API Result Codes Over Time Range" (API Big Stats): added dedicated 4xx panel and 5xx panel
2. Remove Panel "API Response by Status Code and API Call" after review (API Big Stats)
3. EOB Response Time chart (API Big Stats): Display time value in seconds vs milli-seconds and round to 2 digits after decimal for better human consuming experience
4. "Initial Authorization Request / Authorization Completed %" chart (AUTH FLOW Dashboard), correct the title, and improve the percentage display
The dashboards with the changes have been deploy to splunk, see "Validation" section for details
The Dashboards with changes are deployed to Splunk …

jimfuqian/BB2-3466 Usabilities Improve in Splunk Dashboards: auth flow dashboard, api big stats dashboard

---

apps/core/management/commands/create_test_feature_switches.py

[BB2-3346](https://jira.cms.gov/browse/BB2-3346)
[BB2-2871](https://jira.cms.gov/browse/BB2-2871)
This PR adds some waffle switches to our local environment, so that testing locally more closely mimics the behavior we would see in TEST/SBX/PROD. While editing these switches, I also added support for notes to be included in the automatically locally created switches, and put them in alphabetical order.
- Are any of these switches ones that we should omit from local envs for some reason?
- Are these descriptions helpful enough to count as documentation?
Navigate to http://localhost:8000/admin/waffle/switch in your local environment, and compare to the same page in the other environments.
Confirm that …

Add missing switches, alphabetize switches, support notes for switches.

---

apps/dot_ext/urls.py
apps/mymedicare_cb/tests/test_callback_slsx.py
apps/mymedicare_cb/views.py
apps/testclient/views.py
docker-compose/run_selenium_tests_remote.sh

[BB2-3497](https://jira.cms.gov/browse/BB2-3497)
This PR makes all auth requests hit the v2 callback. This is a simple change that doesn't rely on SLS, but helps us eliminate potential confusion caused by an apparent version downgrade in auth and prevent potential forking of auth paths and strategies. Since v1 and v2 auth are the same, this is mostly aimed at preventing confusion among our users, simplifying the logs, and preventing potential forking if we make future changes to the v2 auth path that are not reflected for users starting with v1.
To validate, run locally and use the test client to authorize. After auth, api version should read v2, regardless
* Modifies any security …

BB2-3497: fix auth version redirects

---

apps/capabilities/management/commands/create_blue_button_scopes.py
apps/dot_ext/views/authorization.py
apps/mymedicare_cb/tests/test_callback_slsx.py

[BB2-3796](https://jira.cms.gov/browse/BB2-3796)
Adds support for making POST authenticate requests, while requiring state.  
Tests. You can walk through the steps [here](https://bluebutton.cms.gov/developers/#authorization) to test, but make your request to `/v2/o/authorize` a POST request with the data submitted using -d in your curl request instead of putting it in a query string. NB: If you don't include a state value, you will receive a 401 response. 
etc)

BB2-3796: Allow POST in auth requests

---

apps/core/management/commands/create_test_feature_switches.py
apps/fhir/bluebutton/tests/test_fhir_resources_read_search_w_validation.py
apps/fhir/bluebutton/views/search.py

[BB2-3887](https://jira.cms.gov/browse/BB2-3887)
Add EOB search parameter _tag
1. Added EOB search parameter _tag to the currently supported parameters e.g. _lastUpdated, _service_date etc.
2. Customized validator for _tag where more accurate validation error can be achieved, [Python data validator: voluptuous](https://pypi.org/project/voluptuous/)
Verify that the _tag parameter is only applicable to EOB search:
EOB read won't have it (parameter validator policy for extra : removed)
Patient read/search won't have it (parameter validator policy for extra : removed)
Coverage read/search won't have it (parameter validator policy for extra : removed)
Check parameter value validation:
ADJUDICATED, PARTIALLY-ADJUDICATED are only valid values, other value will be rejected with a …

jimfuqian/BB2-3887 Added search parameter _tag for EOB
